Repository kubevirt/kubevirt.github.io, pull requests merged in 2018-10, with the labels that each got.

#143 Update Rakefile
  Rakefile
Labels: size/XS

#110 initial version of multus blog post
  _posts/2018-09-12-attaching-to-multiple-networks.markdown
Labels: size/L

#142 Include warning about possible conflicts with Weave IP allocation
  pages/ec2.md
  pages/gcp.md
Labels: size/S

#144 Containerized-data-importer Introduction
  _posts/2018-10-09-containerized-data-importer.markdown
Labels: size/L

#146 Add section on where to report push button issues
  pages/ec2.md
  pages/gcp.md
Labels: size/S

#145 post(datavolumes): Add CDI DataVolumes post
  _posts/2018-10-10-CDI-DataVolumes.markdown
Labels: size/L

#147 Kubernetes labs update
  labs/kubernetes/lab6.md
  labs/kubernetes/lab7.md
  labs/manifests/pvc_fedora.yml
Labels: size/M

#148 New images published to fix weave-net conflict issue
  pages/ec2.md
  pages/gcp.md
Labels: size/M

#149 Add missing closing parenthesis
  pages/ec2.md
Labels: size/XS

#150 Rename Kubernetes labs
  _data/labs_toc.yml
  labs/kubernetes/lab1.md
  labs/kubernetes/lab2.md
  pages/ec2.md
  pages/gcp.md
Labels: size/S

#152 vnc removal cleanup
  labs/kubernetes/lab1.md
Labels: size/XS

#157 fix html-proofer errors
  labs/kubernetes/kubernetes.html
  labs/kubernetes/lab1.md
  labs/kubernetes/lab2.md
  labs/labs.html
  labs/ocp/lab0.md
  labs/ocp/lab1.md
  labs/ocp/lab2.md
  labs/ocp/lab3.md
  labs/ocp/lab4.md
  labs/ocp/lab5.md
  labs/ocp/lab6.md
  labs/ocp/lab7.md
  labs/ocp/lab8.md
  labs/ocp/lab9.md
Labels: size/M
