Repository kubevirt/kubevirt.github.io, pull requests merged in 2018-11, with the labels that each got.

#159 Add .html extension to urls to fix HTML-Proofer errors
  _data/labs_toc.yml
Labels: size/XS

#155 Template labs commands into variables
  _data/labs_kubernetes_variables.yml
  labs/kubernetes/lab1.md
  labs/kubernetes/lab2.md
Labels: size/M

#162 New blog about configMap, secret and serviceAccount
  _posts/2018-11-16-new-volume-types.markdown
  labs/ocp/lab1.md
  labs/ocp/lab2.md
Labels: size/L

#140 Quick rehash of network deep-dive with multus
  _posts/2018-10-03-KubeVirt-Network-Rehash.markdown
  assets/images/haproxy_stats.png
  assets/images/skydive_haproxy_to_vm.png
  assets/images/skydive_vm_to_vm.png
Labels: size/L

#168 Add go imports records
  _includes/head.html
  pages/cluster-api-provider-external.md
  pages/node-recovery.md
Labels: size/S

#166 Address missing documentation in get started page
  pages/get_kubevirt.md
Labels: size/S

#161 update kubevirt version
  _config.yml
Labels: size/XS

#170 Blog: Announce KubeCon NA 2018 sessions
  _posts/2018-11-26-kubevirt-at-kubecon-na.markdown
Labels: size/M

#171 Correct Loodse link in KubeCon NA Post
  _posts/2018-11-26-kubevirt-at-kubecon-na.markdown
Labels: size/XS

#172 EC2 images for KubeVirt 0.10.0
  pages/ec2.md
Labels: size/S
