Repository kubevirt/kubevirt.github.io, pull requests merged in 2019-12, with the labels that each got.

#416 Adding KubeVirt lab 1 post with video embed (December 4th)
  _posts/2019-12-04-KubeVirt_lab1_use_kubevirt.md
  labs/kubernetes/lab1.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M

#418 Article on 0.24
  _posts/2019-12-03-changelog-v0.24.0.markdown
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/S

#417 adding kubevirt lab2 video blogpost
  _posts/2019-12-10-KubeVirt_lab2_experiment_with_cdi.md
  labs/kubernetes/lab2.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M

#419 LAB3 - KubeVirt Upgrades
  Jenkinsfile
  _data/labs_toc.yml
  labs/kubernetes/lab2.md
  labs/kubernetes/lab3.md
  tests/README.md
  tests/ansible/lab3.yml
  tests/shell/uninstall-kubevirt.sh
Labels: approved, dco-signoff: yes, kind/enhancement, kind/website, lgtm, size/L

#420 Fix command for ansible lab3
  tests/ansible/lab3.yml
Labels: dco-signoff: yes, kind/bug, size/XS

#421 Add some delays and retries
  tests/ansible/lab3.yml
Labels: dco-signoff: yes

#422 Add sleep to allow operator to create containers
  tests/ansible/lab3.yml
Labels: dco-signoff: yes

#423 Apply Operator to perform upgrade
  tests/ansible/lab3.yml
Labels: dco-signoff: yes

#425 Use podman instead of docker to run local jekyll
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS
