Repository kubevirt/kubevirt.github.io, pull requests merged in 2019-09, with the labels that each got.

#328 Fix broken links
  _posts/2019-04-17-Hyper-Converged-Operator.markdown
Labels: kind/blog, kind/bug, size/XS

#327 Add OGP headers
  _config.yml
  _includes/head.html
  _includes/metas-ogp.html
Labels: approved, kind/enhancement, lgtm, size/S

#325 Add warning for deploying on one node because of hostpath
  labs/kubernetes/lab2.md
Labels: approved, kind/enhancement, lgtm, size/XS

#329 Add release notes
  _posts/2019-09-09-changelog-v0.21.0.markdown
Labels: approved, kind/blog, lgtm, size/S

#330 Provide type article only on posts
  _includes/metas-ogp.html
Labels: approved, lgtm, size/XS

#334 Resize katacoda logo to match final size
  assets/images/katacoda-logo.png
Labels: approved, lgtm, size/XS

#335 adding missing ogp tags type and image
  _config.yml
  _includes/metas-ogp.html
Labels: approved, lgtm, size/XS

#336 Add publication on cncf sandbox
  _posts/2019-09-09-CNCF-Sandbox.md
Labels: approved, kind/blog, lgtm, size/S

#337 Use relative path
  _config.yml
Labels: approved, lgtm, size/XS

#338 Remove trailing
  _includes/metas-ogp.html
Labels: approved, lgtm, size/XS

#340 solves issue with the meta and link closing tags char
  _includes/head.html
  _includes/metas-ogp.html
Labels: approved, kind/blog, lgtm, size/S

#324 Add netlify usage to privacy page
  TODO.md
  pages/privacy.md
Labels: approved, kind/enhancement, lgtm, size/XS

#342 Update lab2
  labs/manifests/storage-setup.yml
  labs/manifests/vm1_pvc.yml
Labels: approved, dco-signoff: yes, lgtm, size/S

#347 Use domain without www
  _config.yml
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, size/XS

#344 Fix images in network deep dive
  _posts/2018-04-25-KubeVirt-Network-Deep-Dive.markdown
  _posts/2018-10-03-KubeVirt-Network-Rehash.markdown
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M

#349 Remove GA code
  _config.yml
  _includes/head.html
Labels: approved, dco-signoff: yes, lgtm, size/S
