Repository kubevirt/kubevirt.github.io, pull requests merged in 2019-06, with the labels that each got.

#236 cdi is now in its own namespace apparently
  _includes/scriptlets/lab2/05_view_cdi_pod_status.sh
Labels: size/XS

#235 [WIP] Blog: vagrant kubevirt provider
  _posts/2019-06-04-Kubevirt-vagrant-provider.markdown
Labels: do-not-merge/work-in-progress, size/L

#242 fix: links on kubevirtci blog post
  _posts/2018-08-08-kubevirtci.markdown
Labels: size/XS

#240 Add owners file
  OWNERS
Labels: size/S

#244 feat: add github templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/S

#243 Use latest kubevirt release
  _includes/scriptlets/quickstart_minikube/04_setenv_version.sh
Labels: size/XS

#247 Fix: Future test problems on Prow
  Gemfile
  Rakefile
Labels: size/XS

#246 fix #213
  README.md
Labels: approved, kind/enhancement, lgtm, size/S

#250 Awstable
  pages/ec2.md
Labels: approved, kind/enhancement, lgtm, size/M

#216 Unify minikube with other labs format and remove trailing files
  _includes/scriptlets/lab1/08_delete_testvm.sh
  _includes/scriptlets/quickstart_minikube/12_create_vm.sh
  _includes/scriptlets/quickstart_minikube/15_delete_vms.sh
  _includes/scriptlets/quickstart_minikube/15_virtctl_start_vm.sh
  _includes/scriptlets/quickstart_minikube/18_virtctl_serial_console.sh
  _includes/scriptlets/quickstart_minikube/20_virtctl_stop_vm.sh
  pages/quickstart_minikube.md
Labels: approved, kind/enhancement, lgtm, size/M

#255 Fix link to old scollier repo
  labs/ocp/lab2.md
Labels: kind/bug, lgtm, size/XS

#257 Fix broken link by pointing to a specific version
  _posts/2018-07-03-Unit-Test-Howto.markdown
Labels: approved, kind/bug, lgtm, size/XS

#259 provide better info on how to locate gcp cloud image
  pages/gcp.md
Labels: approved, kind/enhancement, lgtm, size/XS

#266 Use dots for versions and remove duplicated article
  _posts/2017-11-07-Kube-Virt-v004.markdown
  _posts/2017-12-08-Kube-Virt-v010.markdown
  _posts/2017-12-08-Kube-Virt-v020.markdown
  _posts/2018-01-05-Kube-Virt-v020.markdown
Labels: approved, kind/enhancement, lgtm, size/M

#267 Add links to titles
  pages/blogs/2017/posts.md
  pages/blogs/2018/posts.md
  pages/blogs/2019/posts.md
  pages/blogs/community.md
  pages/blogs/news.md
  pages/blogs/releases.md
  pages/blogs/uncategorized.md
  pages/blogs/updates.md
Labels: approved, kind/bug, kind/enhancement, lgtm, size/S

#271 Fix broken link to requirements
  labs/ocp/lab2.md
Labels: approved, kind/bug, lgtm, size/XS

#278 Add Edu Minguez to community team
  OWNERS
Labels: approved, kind/enhancement, lgtm, size/XS

#252 fix: OWNERS for prow to label issues/prs
  OWNERS
Labels: approved, lgtm, size/M

#248 Update the install guide with the addition of installing via `krew`
  pages/quickstart_minikube.md
Labels: approved, lgtm, size/S

#279 Hide community as it has no articles
  _data/blogs_toc.yml
Labels: approved, kind/enhancement, kind/website, lgtm, size/XS

#270 Generation of changelog entries based on git log
  scripts/update_changelog.sh
Labels: approved, lgtm, size/M

#281 Autorelease
  scripts/update_changelog.sh
Labels: approved, kind/bug, lgtm, size/S
