Repository kubevirt/kubevirt.github.io, pull requests merged in 2019-04, with the labels that each got.

#210 Create test specs for lab1 and lab2 demos
  _includes/scriptlets/lab1/05_verify_testvm_instance.sh
  _includes/scriptlets/lab1/test_spec.yaml
  _includes/scriptlets/lab2/test_spec.yaml
Labels: size/L

#209 Add quickstart test spec
  _includes/scriptlets/quickstart_minikube/04_setenv_version.sh
  _includes/scriptlets/quickstart_minikube/test_spec.yaml
Labels: size/L

#211 Removed old documentation
  _data/docs_toc.yml
  pages/docs/additional-resources.md
  pages/docs/authorization.md
  pages/docs/installation.md
  pages/docs/installation/admission-controllers.md
  pages/docs/installation/feature-matrix.md
  pages/docs/usage.md
  pages/docs/workloads.md
  pages/docs/workloads/annotations-labels.md
  pages/docs/workloads/controllers.md
  pages/docs/workloads/controllers/virtual-machine-replica-set.md
  pages/docs/workloads/controllers/virtual-machine.md
  pages/docs/workloads/templates.md
  pages/docs/workloads/virtual-machines.md
  pages/docs/workloads/vms/create-networkpolicy.md
  pages/docs/workloads/vms/creation.md
  pages/docs/workloads/vms/disks-and-volumes.md
  pages/docs/workloads/vms/dns-for-services.md
  pages/docs/workloads/vms/expose-vm-sevices.md
  pages/docs/workloads/vms/graphical-and-console-access.md
  pages/docs/workloads/vms/guest-os-info.md
  pages/docs/workloads/vms/interfaces-networks.md
  pages/docs/workloads/vms/life-cycle.md
  pages/docs/workloads/vms/node-eviction.md
  pages/docs/workloads/vms/presets.md
  pages/docs/workloads/vms/startup-scripts.md
  pages/docs/workloads/vms/virtual-hardware-config.md
  pages/docs/workloads/vms/vms-to-nodes.md
Labels: size/XXL

#212 Add kubectl version
  assets/images/.DS_Store
  pages/quickstart_minikube.md
Labels: size/XS

#214 Update AWS images to KubeVirt v0.16.1
  _posts/2018-06-21-Run-Istio-with-kubevirt.markdown
  pages/ec2.md
Labels: size/M
