Repository kubevirt/kubevirt.github.io, pull requests merged in 2019-01, with the labels that each got.

#177 Autodeployer gcp blog entry
  _posts/2018-12-13-kubevirt-autolatest.markdown
  assets/images/autodeployer/image.png
  assets/images/autodeployer/instance.png
  assets/images/autodeployer/metadata.png
Labels: do-not-merge/hold, size/M

#169 dont specify a version in gcp doc
  pages/gcp.md
Labels: size/XS

#174 Decouple script fragments from markdown - prepare for testability
  _data/labs_kubernetes_variables.yml
  _includes/scriptlets/get_kubevirt/01_emulate_vm_extensions.sh
  _includes/scriptlets/get_kubevirt/02-a_deploy_with_kubectl.sh
  _includes/scriptlets/get_kubevirt/02-b_deploy_with_oc.sh
  _includes/scriptlets/get_kubevirt/03_get_virtctl.sh
  _includes/scriptlets/get_kubevirt/04_create_vm.sh
  _includes/scriptlets/get_kubevirt/05_vm_consoles.sh
  _includes/scriptlets/get_kubevirt/start_minikube.sh
  _includes/scriptlets/get_kubevirt/verify_nested_virt.sh
  _includes/scriptlets/kubevirt-ansible/clone_ansible.sh
  _includes/scriptlets/kubevirt-ansible/gluster-heketi-inventory-template.yml
  _includes/scriptlets/kubevirt-ansible/playbook-gluster-heketi.sh
  _includes/scriptlets/kubevirt-ansible/playbook_no_storage.sh
  _includes/scriptlets/kubevirt-ansible/playbook_with_storage.sh
  _includes/scriptlets/kubevirt-ansible/storage-inventory-template.yml
  _includes/scriptlets/lab1/01_get_vm_manifest.sh
  _includes/scriptlets/lab1/02_create_testvm.sh
  _includes/scriptlets/lab1/03_verify_testvm.sh
  _includes/scriptlets/lab1/04_start_testvm.sh
  _includes/scriptlets/lab1/05_verify_testvm_instance.sh
  _includes/scriptlets/lab1/06_connect_to_testvm_console.sh
  _includes/scriptlets/lab1/07_stop_testvm.sh
  _includes/scriptlets/lab1/08_delete_testvm.sh
  _includes/scriptlets/lab2/01_get_storage_manifest.sh
  _includes/scriptlets/lab2/02_get_cdi_controller_manifest.sh
  _includes/scriptlets/lab2/03_create_storage.sh
  _includes/scriptlets/lab2/04_create_cdi-controller.sh
  _includes/scriptlets/lab2/05_view_cdi_pod_status.sh
  _includes/scriptlets/lab2/06_create_fedora_cloud_instance.sh
  _includes/scriptlets/lab2/07_view_pod_logs.sh
  _includes/scriptlets/lab2/08_get_vm_manifest.sh
  _includes/scriptlets/lab2/09_create_vm1.sh
  _includes/scriptlets/lab2/10_view_pods.sh
  _includes/scriptlets/lab2/11_view_vm_in_qemu.sh
  _includes/scriptlets/lab2/12_connect_to_vm1_console.sh
  _includes/scriptlets/lab2/13_ssh_to_vm1.sh
  labs/kubernetes/lab1.md
  labs/kubernetes/lab2.md
  pages/get_kubevirt.md
Labels: size/L

#179 KubeVirt v0.13.0 updates
  _includes/scriptlets/lab1/01_get_vm_manifest.sh
  _includes/scriptlets/lab1/02_create_testvm.sh
  _includes/scriptlets/lab2/02_get_cdi_controller_manifest.sh
  labs/manifests/vm.yaml
  labs/manifests/vm1_pvc.yml
Labels: size/M

#181 Fix typos
  _includes/scriptlets/lab1/01_get_vm_manifest.sh
  _includes/scriptlets/lab1/02_create_testvm.sh
  _includes/scriptlets/lab2/08_get_vm_manifest.sh
Labels: size/XS

#182 KubeVirt 0.13.2 AMIs
  _posts/2018-06-07-Non-Dockerized-Build.markdown
  pages/ec2.md
Labels: size/M

#180 post: metrics
  _posts/2019-01-22-An-overview-to-KubeVirt-metrics.markdown
  assets/2018-12-24-An-overview-to-KubeVirt-metrics/grafana_1.png
  assets/2018-12-24-An-overview-to-KubeVirt-metrics/grafana_thresholds.png
  assets/2018-12-24-An-overview-to-KubeVirt-metrics/promui_1.png
  assets/2018-12-24-An-overview-to-KubeVirt-metrics/promui_2.png
Labels: size/L
