Repository kubevirt/kubevirt.github.io, pull requests merged in 2019-03, with the labels that each got.

#190 Add go import record for kubevirt.io/cloud-provider-kubevirt
  _includes/head.html
  pages/cloud-provider-kubevirt.md
Labels: size/XS

#167 Blog on ignition data support
  _posts/2018-11-20-ignition-support.markdown
Labels: do-not-merge/release-note-label-needed, size/L

#191 Added virt check and create namespace in k8s
  _includes/scriptlets/get_kubevirt/00_create_kubevirt_namespace.sh
  _includes/scriptlets/get_kubevirt/00_verify_virtualization.sh
  pages/get_kubevirt.md
Labels: size/S

#192 fix cdi link
  _posts/2018-10-09-containerized-data-importer.markdown
Labels: size/XS

#193 Deploy with operator
  _includes/scriptlets/get_kubevirt/00_create_kubevirt_namespace.sh
  _includes/scriptlets/get_kubevirt/00_deploy_operator.sh
  _includes/scriptlets/get_kubevirt/01_a_verify_virtualization.sh
  _includes/scriptlets/get_kubevirt/01_b_emulate_vm_extensions.sh
  _includes/scriptlets/get_kubevirt/02-a_deploy_with_kubectl.sh
  _includes/scriptlets/get_kubevirt/02-b_deploy_with_oc.sh
  _includes/scriptlets/get_kubevirt/02_deploy_kubevirt.sh
  pages/get_kubevirt.md
Labels: size/M

#198 minor typo
  _config.yml
  pages/get_kubevirt.md
Labels: size/XS

#201 Correct variable in deploy script
  _includes/scriptlets/get_kubevirt/02_deploy_kubevirt.sh
Labels: size/XS

#200 update urls for vm.yaml
  _includes/scriptlets/get_kubevirt/04_create_vm.sh
Labels: size/XS

#202 fix: get_kubevirt guide
  README.md
  _includes/scriptlets/get_kubevirt/00_deploy_operator.sh
  _includes/scriptlets/get_kubevirt/01_a_verify_virtualization.sh
  _includes/scriptlets/get_kubevirt/01_b_emulate_vm_extensions.sh
  _includes/scriptlets/get_kubevirt/02_deploy_kubevirt.sh
  _includes/scriptlets/get_kubevirt/03_get_virtctl.sh
  _includes/scriptlets/get_kubevirt/04_create_vm.sh
  _includes/scriptlets/get_kubevirt/05_vm_consoles.sh
  _includes/scriptlets/get_kubevirt/start_minikube.sh
  _includes/scriptlets/quickstart_minikube/00_verify_nested_virt.sh
  _includes/scriptlets/quickstart_minikube/01_minikube_config_memory.sh
  _includes/scriptlets/quickstart_minikube/02_minikube_config_vm_driver.sh
  _includes/scriptlets/quickstart_minikube/03_start_minikube.sh
  _includes/scriptlets/quickstart_minikube/04_setenv_version.sh
  _includes/scriptlets/quickstart_minikube/05_deploy_operator.sh
  _includes/scriptlets/quickstart_minikube/06_check_operator_running.sh
  _includes/scriptlets/quickstart_minikube/07_verify_virtualization.sh
  _includes/scriptlets/quickstart_minikube/08_emulate_vm_extensions.sh
  _includes/scriptlets/quickstart_minikube/09_deploy_kubevirt.sh
  _includes/scriptlets/quickstart_minikube/11_get_virtctl.sh
  _includes/scriptlets/quickstart_minikube/12_create_vm.sh
  _includes/scriptlets/quickstart_minikube/13_get_vms.sh
  _includes/scriptlets/quickstart_minikube/14_get_vms_yaml.sh
  _includes/scriptlets/quickstart_minikube/15_delete_vms.sh
  _includes/scriptlets/quickstart_minikube/15_virtctl_start_vm.sh
  _includes/scriptlets/quickstart_minikube/16_get_vmis.sh
  _includes/scriptlets/quickstart_minikube/17_get_vmis_yaml.sh
  _includes/scriptlets/quickstart_minikube/18_virtctl_serial_console.sh
  _includes/scriptlets/quickstart_minikube/19_virtctl_vnc_console.sh
  _includes/scriptlets/quickstart_minikube/20_virtctl_stop_vm.sh
  _includes/scriptlets/quickstart_minikube/21_kubectl_delete_vm.sh
  _includes/scriptlets/quickstart_minikube/22_minikube_delete.sh
  _layouts/homepage.html
  assets/images/ui_vm_pod_1.png
  assets/images/ui_vm_pod_2.png
  pages/community/contributing.md
  pages/get_kubevirt.md
  pages/quickstart_minikube.md
Labels: size/L

#206 issue205: Add redirect for get_kubevirt
  Gemfile
  _config.yml
  pages/quickstart_minikube.md
Labels: size/XS

#204 Metrics followup: setup, troubleshooting, VM metrics
  _posts/2019-03-14-More-about-Kubevirt-metrics.markdown
  assets/2019-03-14-More-about-KubeVirt-metrics/promui_graphs.png
  assets/2019-03-14-More-about-KubeVirt-metrics/promui_targets_1.png
Labels: size/L

#207 fix(blog): Images for metrics blog post
  assets/2019-03-14-More-about-KubeVirt-metrics/promui_graphs.png
  assets/2019-03-14-More-about-KubeVirt-metrics/promui_targets_1.png
Labels: size/XS

#208 Add caveat about older Minikube which lacks vhost-net device
  pages/quickstart_minikube.md
Labels: size/XS
