Repository kubevirt/kubevirt.github.io, pull requests merged in 2019-05, with the labels that each got.

#218 Updating documentation to add clarity
  _includes/scriptlets/lab2/02_get_cdi_controller_manifest.sh
  _includes/scriptlets/lab2/07_view_pod_logs.sh
Labels: size/XS

#219 Have blog titles be links in /blogs/
  blogs/index.html
Labels: size/XS

#217 Remove 'example' from header
  README.md
Labels: size/XS

#220 Fix font size on blog post headers
  _sass/_typography.scss
Labels: size/XS

#221 Fix typo
  _posts/2018-12-13-kubevirt-autolatest.markdown
Labels: size/XS

#222 Blog: kubevirt+ansible part 1
  _posts/2019-05-21-kubevirt-with-ansible-part-1.markdown
Labels: size/L

#225 Separate posts in 2019
  _data/blogs_toc.yml
  pages/blogs/2019/posts.md
Labels: enhancement, size/M

#223 Do not hardcode server uri, use relative path
  _data/site_nav_pages.yml
Labels: size/XS

#230 Announce feed in headers
  Gemfile
  _config.yml
  _includes/head.html
  feed.xml
Labels: size/M

#234 Update link not to be broken anymore
  _posts/2017-09-29-This-Week-in-Kube-Virt-4.markdown
Labels: size/XS

#232 Enable sitemap generation for web crawlers
  Gemfile
  _config.yml
Labels: kind/enhancement, size/XS

#231 Generate feeds for categories
  _config.yml
Labels: size/XS
