Repository kubevirt/kubevirt.github.io, pull requests merged in 2019-02, with the labels that each got.

#186 Instruct user to use latest image for gcp
  assets/images/kubevirt-button/create_image.png
  pages/gcp.md
Labels: size/XS

#183 KubeVirt 0.14.0 AWS images
  pages/ec2.md
Labels: size/S

#188 federated kubevirt blog
  _posts/2019-02-22-federated-kubevirt.markdown
  assets/2019-02-22-federated-kubevirt/federated_cm.yaml
  assets/2019-02-22-federated-kubevirt/federated_kubevirt-cr.yaml
  assets/2019-02-22-federated-kubevirt/federated_kubevirt-operator.yaml
  assets/2019-02-22-federated-kubevirt/federated_namespace.yaml
  assets/2019-02-22-federated-kubevirt/federated_pvc.yaml
  assets/2019-02-22-federated-kubevirt/federated_vm.yaml
Labels: size/L
