Repository kubevirt/kubevirt.github.io, pull requests merged in 2019-10, with the labels that each got.

#357 Update Rakefile for domain without www
  Rakefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#358 Adjust heading levels
  _posts/2019-10-09-KubeVirt_k8s_crio_from_scratch.md
Labels: dco-signoff: yes, kind/blog, size/S

#360 Clarifies running lab2 on minikube - issue #351
  _includes/scriptlets/lab2/14_minikube_ssh_vm1.sh
  _includes/scriptlets/lab2/15_minikube_virtctl_expose_ssh_nodeport.sh
  _includes/scriptlets/lab2/16_minikube_vm_ip.sh
  _includes/scriptlets/lab2/17_ssh_from_outer_minikube.sh
  labs/kubernetes/lab2.md
  labs/manifests/vm1_pvc.yml
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/M

#352 #issue 350 - Added storageclass hostpath to pvc and decreased the size to also work on minikube
  labs/manifests/pvc_fedora.yml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#364 Add v022 release notes
  _posts/2019-10-10-changelog-v0.22.0.markdown
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/S

#366 Feat: Rakefile param to avoid url_swap on demand
  Rakefile
Labels: approved, dco-signoff: yes, lgtm, size/S

#367 fixing naming, KubeVirt instead of Kube Virt
  scripts/update_changelog.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#368 Adjust naming of KubeVirt
  _posts/2018-03-08-changelog-v0.3.0.markdown
  _posts/2018-04-06-changelog-v0.4.0.markdown
  _posts/2018-05-04-changelog-v0.5.0.markdown
  _posts/2018-05-16-KubeVirt-API-Access-Control.markdown
  _posts/2018-06-03-Research-run-VMs-with-istio-service-mesh.markdown
  _posts/2018-06-11-changelog-v0.6.0.markdown
  _posts/2018-06-20-Hello-KubeVirt-on-Minikube.markdown
  _posts/2018-07-04-changelog-v0.7.0.markdown
  _posts/2018-07-23-Kubevirt-v0.7.0.markdown
  _posts/2018-08-08-kubevirtci.markdown
  _posts/2018-09-06-changelog-v0.8.0.markdown
  _posts/2018-10-04-changelog-v0.9.0.markdown
  _posts/2018-10-09-containerized-data-importer.markdown
  _posts/2018-11-08-changelog-v0.10.0.markdown
  _posts/2018-11-20-ignition-support.markdown
  _posts/2018-12-06-changelog-v0.11.0.markdown
  _posts/2018-12-13-kubevirt-autolatest.markdown
  _posts/2019-01-11-changelog-v0.12.0.markdown
  _posts/2019-01-15-changelog-v0.13.0.markdown
  _posts/2019-01-22-An-overview-to-KubeVirt-metrics.markdown
  _posts/2019-02-04-changelog-v0.14.0.markdown
  _posts/2019-02-22-federated-kubevirt.markdown
  _posts/2019-03-05-changelog-v0.15.0.markdown
  _posts/2019-04-05-changelog-v0.16.0.markdown
  _posts/2019-05-06-changelog-v0.17.0.markdown
  _posts/2019-06-04-Kubevirt-vagrant-provider.markdown
  _posts/2019-06-05-changelog-v0.18.0.markdown
  _posts/2019-07-05-changelog-v0.19.0.markdown
  _posts/2019-07-29-How-To-Import-VM-into-Kubevirt.markdown
  _posts/2019-08-01-KubeVirt-CR-Condition-Types-Rename.markdown
  _posts/2019-08-09-Kubevirt-CR-Condition-Types-Rename-Now-ACTIVE.markdown
  _posts/2019-08-09-changelog-v0.20.0.markdown
  _posts/2019-09-09-changelog-v0.21.0.markdown
  _posts/2019-10-10-changelog-v0.22.0.markdown
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/L

#370 Adding second blogpost and changing first post to point to the second one
  _posts/2019-10-09-KubeVirt_k8s_crio_from_scratch.md
  _posts/2019-10-16-KubeVirt_k8s_crio_from_scratch_installing_kubernetes.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/L

#375 Cloud image changed from qcow2 to raw since Fedora CDN not supporting range
  labs/manifests/pvc_fedora.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#376 Clarified access to vm1 in lab2
  labs/kubernetes/lab2.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#378 Fix URL for using the CIB artifacts
  tests/ansible/aws-provision.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#369 Change bot name
  _posts/2018-03-08-changelog-v0.3.0.markdown
  _posts/2018-04-06-changelog-v0.4.0.markdown
  _posts/2018-05-04-changelog-v0.5.0.markdown
  _posts/2018-06-11-changelog-v0.6.0.markdown
  _posts/2018-07-04-changelog-v0.7.0.markdown
  _posts/2018-09-06-changelog-v0.8.0.markdown
  _posts/2018-10-04-changelog-v0.9.0.markdown
  _posts/2018-11-08-changelog-v0.10.0.markdown
  _posts/2018-12-06-changelog-v0.11.0.markdown
  _posts/2019-01-11-changelog-v0.12.0.markdown
  _posts/2019-01-15-changelog-v0.13.0.markdown
  _posts/2019-02-04-changelog-v0.14.0.markdown
  _posts/2019-03-05-changelog-v0.15.0.markdown
  _posts/2019-04-05-changelog-v0.16.0.markdown
  _posts/2019-05-06-changelog-v0.17.0.markdown
  _posts/2019-06-05-changelog-v0.18.0.markdown
  _posts/2019-07-05-changelog-v0.19.0.markdown
  _posts/2019-08-09-changelog-v0.20.0.markdown
  _posts/2019-09-09-changelog-v0.21.0.markdown
  _posts/2019-10-10-changelog-v0.22.0.markdown
  scripts/update_changelog.sh
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M

#379 Third blogpost of the series of 3
  _posts/2019-10-23-KubeVirt_k8s_crio_from_scratch_installing_KubeVirt.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/L

#381 K8s third blogpost modifications (add links between blogposts)
  _posts/2019-10-09-KubeVirt_k8s_crio_from_scratch.md
  _posts/2019-10-16-KubeVirt_k8s_crio_from_scratch_installing_kubernetes.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XS

#363 Adding resources needed to run the blog post and information about deploying
  _posts/2019-10-09-KubeVirt_k8s_crio_from_scratch.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, ok-to-test, size/XS

#377 Point to cloud-image-builder repo and adjust format
  tests/README.md
  tests/shell/lab.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#382 adding a link in the end of the post to the next blogpost in the series
  _posts/2019-10-16-KubeVirt_k8s_crio_from_scratch_installing_kubernetes.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XS

#383 Pep feedback changes
  _posts/2019-10-09-KubeVirt_k8s_crio_from_scratch.md
  _posts/2019-10-16-KubeVirt_k8s_crio_from_scratch_installing_kubernetes.md
  _posts/2019-10-23-KubeVirt_k8s_crio_from_scratch_installing_KubeVirt.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XS

#384 Change to tests folder before starting the test
  tests/shell/lab.sh
  tests/shell/provision-and-destroy.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#385 Simplify CD
  tests/shell/lab.sh
  tests/shell/provision-and-destroy.sh
Labels: dco-signoff: yes, size/XS

#387 Validationbatch1
  Jenkinsfile
  tests/ansible/lab2.yml
  tests/shell/lab.sh
Labels: dco-signoff: yes, size/M

#388 Change the name of the machine-remediation-operator repository
  _includes/head.html
  pages/machine-remediation-operator.md
  pages/machine-remediation.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#389 adding rook blogpost
  _posts/2019-10-30-KubeVirt_storage_rook_ceph.md
  assets/2019-10-30-KubeVirt_storage_rook_ceph/Ceph_Logo_Standard_RGB_120411_fa_250.png
  assets/2019-10-30-KubeVirt_storage_rook_ceph/rook-stacked-color_250.png
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XL

#390 Adjust playbooks for Lab validation
  tests/ansible/gcp-cleanup.yml
  tests/ansible/gcp-provision.yml
  tests/ansible/lab1.yml
  tests/ansible/lab2.yml
  tests/ansible/minikube-cleanup.yml
Labels: approved, dco-signoff: yes, lgtm, size/M

#371 Prow documentation update
  _posts/2019-07-12-website-roadmap.markdown
  _posts/2019-08-01-KubeVirt-CR-Condition-Types-Rename.markdown
  _posts/2019-08-09-Kubevirt-CR-Condition-Types-Rename-Now-ACTIVE.markdown
  _posts/2019-10-31-prow-jobs-for-kubevirt.markdown
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M
