Repository kubevirt/kubevirt.github.io, pull requests merged in 2019-11, with the labels that each got.

#394 Modified storage class PV path to /var/lib/minikube in all labs
  labs/manifests/storage-setup.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#395 Add 0.23 release notes
  _posts/2019-11-04-changelog-v0.23.0.markdown
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/S

#396 Labimprovements
  Jenkinsfile
  tests/ansible/gcp-provision.yml
  tests/ansible/lab2.yml
Labels: dco-signoff: yes, size/M

#386 Initial jenkins doc
  _posts/2019-10-31-jenkins-jobs-for-kubevirt-lab-validation.markdown
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M

#397 Change subject of slack notifications
  Jenkinsfile
Labels: dco-signoff: yes, size/XS

#398 Throw exception directly on Jenkins Failure
  Jenkinsfile
Labels: dco-signoff: yes

#400 Save artifacts in Jenkinsfile
  Jenkinsfile
Labels: dco-signoff: yes

#401 Don't assume we are operating out of $HOME
  labs/kubernetes/lab2.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#404 Remove duplicated '/'
  _posts/2019-04-17-Hyper-Converged-Operator.markdown
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XS

#405 Update Owners
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#402 Document Jenkins upgrade and changes
  _posts/2019-11-22-jenkins-ci-server-upgrade-and-jobs-for-kubevirt.markdown
  assets/2019-11-22-jenkins-ci-server-upgrade-and-jobs-for-kubevirt/2019-11-11-09-44-56.png
  assets/2019-11-22-jenkins-ci-server-upgrade-and-jobs-for-kubevirt/2019-11-11-09-46-47.png
  assets/2019-11-22-jenkins-ci-server-upgrade-and-jobs-for-kubevirt/2019-11-11-09-51-19.png
  assets/2019-11-22-jenkins-ci-server-upgrade-and-jobs-for-kubevirt/2019-11-11-09-54-24.png
  assets/2019-11-22-jenkins-ci-server-upgrade-and-jobs-for-kubevirt/2019-11-11-09-55-41.png
  assets/2019-11-22-jenkins-ci-server-upgrade-and-jobs-for-kubevirt/2019-11-11-11-02-34.png
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/L

#406 [blog] Add blog post about KubeVirt at KubeCon
  _posts/2019-11-12-kubecon-na-2019.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M

#407 KubeCon blog post: fix link
  _posts/2019-11-12-kubecon-na-2019.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XS

#408 Typo fixed in the blogpost about KubeCon and KubeVirt
  _posts/2019-11-12-kubecon-na-2019.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XS

#403 Access Virtual Machines' graphic console using noVNC
  _posts/2019-11-11-Access-Virtual-Machines-graphic-console-using-noVNC.markdown
  assets/2019-11-11-Access-Virtual-Machines-graphic-console-using-noVNC/virtvnc.gif
Labels: approved, dco-signoff: yes, kind/blog, lgtm, ok-to-test, size/L

#410 Fix typo
  _posts/2018-10-09-containerized-data-importer.markdown
  _posts/2019-11-11-Access-Virtual-Machines-graphic-console-using-noVNC.markdown
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M

#412 Revert "Fix typo"
  _posts/2019-11-11-Access-Virtual-Machines-graphic-console-using-noVNC.markdown
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M

#413 Reenable minikube testing
  Jenkinsfile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#414 Adding Kubevirt basicops video blogpost
  _posts/2019-11-28-KubeVirt_basic_operations_video.md
  pages/videos/tech-demos.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M
