Repository kubevirt/kubevirt.github.io, pull requests merged in 2019-07, with the labels that each got.

#282 Adjust owners of project
  OWNERS
Labels: approved, lgtm, size/XS

#274 Deprecate OCP Labs which are not mantained
  labs/ocp/appendices.md
  labs/ocp/lab0.md
  labs/ocp/lab1.md
  labs/ocp/lab2.md
  labs/ocp/lab3.md
  labs/ocp/lab4.md
  labs/ocp/lab5.md
  labs/ocp/lab6.md
  labs/ocp/lab7.md
  labs/ocp/lab8.md
  labs/ocp/lab9.md
  labs/ocp/ocp.html
Labels: approved, kind/bug, kind/website, lgtm, size/XXL

#276 Show minikube on labs like GCP or AWS
  _data/labs_toc.yml
  pages/quickstart_minikube.md
Labels: approved, kind/enhancement, kind/website, lgtm, size/XS

#275 Show labs in menu
  _data/site_nav_pages.yml
  pages/labs.md
Labels: approved, kind/enhancement, kind/website, lgtm, size/S

#285 Replace absolute link for macro post_url
  _posts/2019-03-14-More-about-Kubevirt-metrics.markdown
Labels: approved, kind/blog, kind/enhancement, lgtm, size/XS

#283 Ansible modules introduction, part2
  _posts/2019-07-08-kubevirt-with-ansible-part-2.markdown
Labels: approved, kind/blog, lgtm, size/L

#284 Updates to ansible post part 1
  _posts/2019-05-21-kubevirt-with-ansible-part-1.markdown
Labels: approved, kind/blog, lgtm, size/S

#253 doc: initial work for contents guidelines
  GUIDELINES.md
  README.md
Labels: approved, lgtm, size/L

#277 Add missing changelogs
  _posts/2018-03-08-changelog-v0.3.0.markdown
  _posts/2018-04-06-changelog-v0.4.0.markdown
  _posts/2018-05-04-changelog-v0.5.0.markdown
  _posts/2018-06-11-changelog-v0.6.0.markdown
  _posts/2018-07-04-changelog-v0.7.0.markdown
  _posts/2018-09-06-changelog-v0.8.0.markdown
  _posts/2018-10-04-changelog-v0.9.0.markdown
  _posts/2018-11-08-changelog-v0.10.0.markdown
  _posts/2018-12-06-changelog-v0.11.0.markdown
  _posts/2019-01-11-changelog-v0.12.0.markdown
  _posts/2019-01-15-changelog-v0.13.0.markdown
  _posts/2019-02-04-changelog-v0.14.0.markdown
  _posts/2019-03-05-changelog-v0.15.0.markdown
  _posts/2019-04-05-changelog-v0.16.0.markdown
  _posts/2019-05-06-changelog-v0.17.0.markdown
  _posts/2019-06-05-changelog-v0.18.0.markdown
Labels: approved, kind/blog, kind/enhancement, lgtm, size/L

#286 Updating .qcow image URL to work around intermittent DNS issues on AWS
  labs/manifests/pvc_fedora.yml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#288 Replace links as it was failing with GitHub Pages build
  GUIDELINES.md
Labels: approved, kind/bug, kind/website, lgtm, size/S

#291 Add Pedro to owners
  OWNERS
Labels: approved, lgtm, size/XS

#292 Move relocations to emeritus
  OWNERS
Labels: approved, lgtm, size/S

#290 Update Git ignore
  .gitignore
Labels: approved, kind/enhancement, lgtm, size/XS

#289 Revert "Replace links as it was failing with GitHub Pages build"
  GUIDELINES.md
Labels: approved, kind/enhancement, lgtm, size/S

#293 Add TODO of pending ideas to define on the website
  TODO.md
  _config.yml
Labels: approved, kind/enhancement, lgtm, size/S

#294 Add Post about TODO.md for call to action
  _posts/2019-07-12-website-roadmap.markdown
Labels: approved, kind/blog, kind/enhancement, kind/website, lgtm, size/S

#295 Remove EC2 reference from GCP page
  pages/gcp.md
Labels: approved, lgtm, size/XS

#280 June hco pr
  _posts/2019-04-17-Hyper-Converged-Operator.markdown
  assets/2019-04-17-HyperConvergedOperator/HCO-Managed-Operators.png
  assets/2019-04-17-HyperConvergedOperator/Installed-operator-HCO-48.png
  assets/2019-04-17-HyperConvergedOperator/catalog-operator-32.png
  assets/2019-04-17-HyperConvergedOperator/kubevirt-hco-pods-15.png
  assets/2019-04-17-HyperConvergedOperator/kubevirt-hyperconverged-31.png
  assets/2019-04-17-HyperConvergedOperator/kubevirt-operator-57.png
  assets/2019-04-17-HyperConvergedOperator/status-pods-54.png
  assets/2019-04-17-HyperConvergedOperator/subscription.png
Labels: approved, kind/blog, lgtm, ok-to-test, size/L

#296 Added go-import meta data for new kubevirt/client-go repository
  _includes/head.html
Labels: approved, lgtm, size/XS

#297 Added page needed for go import of kubevirt/client-go.
  pages/client-go.md
Labels: approved, lgtm, size/XS

#299 Add FAQ in TODO
  TODO.md
Labels: approved, kind/enhancement, lgtm, size/XS

#302 fixing issues/300
  _includes/scriptlets/quickstart_minikube/04_setenv_version.sh
Labels: approved, lgtm, size/XS

#228 Import-VM-BlogPost
  _posts/2019-07-29-How-To-Import-VM-into-Kubevirt.markdown
  labs/kubernetes/lab1.md
Labels: approved, kind/blog, lgtm, size/L

#237 NMO-BlogPost
  _posts/2019-07-30-NodeDrain-KubeVirt.markdown
Labels: approved, kind/blog, lgtm, size/L
