Repository kubevirt/kubevirt.github.io, pull requests merged in 2019-08, with the labels that each got.

#306 Alert on CR Condition Rename
  _posts/2019-08-01-Kubevirt-CR-Condition-Types-Rename.markdown
Labels: approved, kind/blog, kind/enhancement, lgtm, size/M

#308 Add replace node-recovery repo with machine-remediation-operator
  _includes/head.html
Labels: size/XS

#309 Change node-recovery page to machine-remediation-operator
  pages/machine-remediation-operator.md
  pages/node-recovery.md
Labels: size/S

#307 add kubectl virt to lab1.md
  labs/kubernetes/lab1.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#310 Add release 0.19.0 post
  _posts/2019-07-05-changelog-v0.19.0.markdown
Labels: approved, kind/blog, lgtm, size/M

#312 Use 'master' URL to use Fedora MirrorManager to redirect
  labs/manifests/pvc_fedora.yml
Labels: approved, lgtm, size/XS

#249 Include 'try it on katacoda' on mainpage
  _layouts/homepage.html
  assets/images/katacoda-logo.png
Labels: approved, kind/enhancement, kind/website, lgtm, size/S

#313 ansible2: update cdi info
  _posts/2019-07-08-kubevirt-with-ansible-part-2.markdown
Labels: approved, kind/blog, lgtm, size/XS

#318 Fixing #303, updating deployment of CDI component using operator on lab2
  _includes/scriptlets/lab2/02_create_storage.sh
  _includes/scriptlets/lab2/02_get_cdi_controller_manifest.sh
  _includes/scriptlets/lab2/03_deploy_cdi_operator.sh
  _includes/scriptlets/lab2/04_create_cdi-controller.sh
  _includes/scriptlets/lab2/04_create_cdi-cr.sh
  labs/kubernetes/lab2.md
Labels: approved, lgtm, size/S

#316 Added tests to Try It Button on Kubevirt.io.
  Jenkinsfile
  tests/README.md
  tests/ansible/aws-cleanup.yml
  tests/ansible/aws-provision.yml
  tests/ansible/gcp-cleanup.yml
  tests/ansible/gcp-provision.yml
  tests/ansible/lab1.yml
  tests/ansible/lab2.yml
  tests/ansible/minikube-cleanup.yml
  tests/ansible/minikube-provision.yml
  tests/config/environment.aws
  tests/config/environment.gcp
  tests/expect/cirros-login.exp
  tests/shell/cleanup.sh
  tests/shell/disable-hostpath-minikube.sh
  tests/shell/lab.sh
  tests/shell/provision-and-destroy.sh
Labels: approved, lgtm, size/XL

#321 Remove gem install as it's done via bundle
  .travis.yml
Labels: approved, kind/enhancement, lgtm, size/XS

#322 Parameter for gtag
  _config.yml
  _includes/head.html
Labels: approved, lgtm, size/XS
