Repository kubevirt/kubevirt.github.io, pull requests merged in 2020-01, with the labels that each got.

#427 Fix virtctl image-upload command
  _posts/2019-07-29-How-To-Import-VM-into-Kubevirt.markdown
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XS

#429 Prepend url to ogimage
  _config.yml
  _includes/metas-ogp.html
  assets/images/KubeVirt_logo_color.png
Labels: dco-signoff: yes, size/XS

#430 Reduce logo to favicon
  assets/images/KubeVirt_logo_color.png
Labels: dco-signoff: yes

#431 Release 0.25
  _posts/2020-01-13-changelog-v0.25.0.markdown
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/S

#435 Update DTM -> DPAL code for analytics
  _includes/head.html
  _layouts/default.html
Labels: approved, dco-signoff: yes, kind/website, lgtm, size/XS

#436 Use month long name
  _posts/2018-03-08-changelog-v0.3.0.markdown
  _posts/2018-04-06-changelog-v0.4.0.markdown
  _posts/2018-06-11-changelog-v0.6.0.markdown
  _posts/2018-07-04-changelog-v0.7.0.markdown
  _posts/2018-09-06-changelog-v0.8.0.markdown
  _posts/2018-10-04-changelog-v0.9.0.markdown
  _posts/2018-11-08-changelog-v0.10.0.markdown
  _posts/2018-12-06-changelog-v0.11.0.markdown
  _posts/2019-01-11-changelog-v0.12.0.markdown
  _posts/2019-01-15-changelog-v0.13.0.markdown
  _posts/2019-02-04-changelog-v0.14.0.markdown
  _posts/2019-03-05-changelog-v0.15.0.markdown
  _posts/2019-04-05-changelog-v0.16.0.markdown
  _posts/2019-06-05-changelog-v0.18.0.markdown
  _posts/2019-07-05-changelog-v0.19.0.markdown
  _posts/2019-08-09-changelog-v0.20.0.markdown
  _posts/2019-09-09-changelog-v0.21.0.markdown
  _posts/2019-10-10-changelog-v0.22.0.markdown
  _posts/2019-11-04-changelog-v0.23.0.markdown
  _posts/2019-12-03-changelog-v0.24.0.markdown
  _posts/2020-01-13-changelog-v0.25.0.markdown
  scripts/update_changelog.sh
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M

#432 Kubevirt lab3 video blogpost
  _posts/2020-01-21-KubeVirt_lab3_upgrade.md
  labs/kubernetes/lab2.md
  labs/kubernetes/lab3.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M

#437 Add spacing in headers
  _includes/metas-ogp.html
Labels: approved, dco-signoff: yes, lgtm, size/XS

#428 Add blog post: Managing KubeVirt with Openshift Web Console
  _posts/2020-01-24-OKD-web-console-install.md
  assets/2020-01-24-OKD-web-console-install/OKD-console-kubevirt.png
  assets/2020-01-24-OKD-web-console-install/console-kubevirt-plugin.png
  assets/2020-01-24-OKD-web-console-install/okd-console-4.5.png
  assets/2020-01-24-OKD-web-console-install/okd-console-4.5.resized.png
  assets/2020-01-24-OKD-web-console-install/okd-console-vm.png
  assets/2020-01-24-OKD-web-console-install/okd-console-vm.resized.png
  assets/2020-01-24-OKD-web-console-install/okd-pod-4.2.png
  assets/2020-01-24-OKD-web-console-install/okd-pod-4.2.resized.png
  assets/2020-01-24-OKD-web-console-install/okd-serviceaccount-error.png
  assets/2020-01-24-OKD-web-console-install/okd-web-console-install.yaml
  assets/2020-01-24-OKD-web-console-install/quay-okd-repo.png
  assets/2020-01-24-OKD-web-console-install/quay-okd-repo.resized.png
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XL

#438 Uselocallinks
  _posts/2019-04-17-Hyper-Converged-Operator.markdown
  _posts/2019-05-21-kubevirt-with-ansible-part-1.markdown
  _posts/2019-07-29-How-To-Import-VM-into-Kubevirt.markdown
  _posts/2019-07-30-NodeDrain-KubeVirt.markdown
  _posts/2019-12-04-KubeVirt_lab1_use_kubevirt.md
  _posts/2019-12-10-KubeVirt_lab2_experiment_with_cdi.md
  _posts/2019-12-17-KubeVirt_UI_options.md
  _posts/2020-01-21-KubeVirt_lab3_upgrade.md
  labs/kubernetes/lab2.md
Labels: approved, dco-signoff: yes, kind/blog, kind/enhancement, lgtm, size/M

#440 Usetravis
  .travis.yml
Labels: dco-signoff: yes, size/S

#439 Adding quickstart_kind lab scenario
  _data/labs_toc.yml
  _includes/scriptlets/quickstart_kind/00_verify_nested_virt.sh
  _includes/scriptlets/quickstart_kind/01_setup_cluster.sh
  _includes/scriptlets/quickstart_kind/02_setenv_version.sh
  _includes/scriptlets/quickstart_kind/03_deploy_operator.sh
  _includes/scriptlets/quickstart_kind/04_check_operator_running.sh
  _includes/scriptlets/quickstart_kind/05_verify_virtualization.sh
  _includes/scriptlets/quickstart_kind/06_emulate_vm_extensions.sh
  _includes/scriptlets/quickstart_kind/07_deploy_kubevirt.sh
  _includes/scriptlets/quickstart_kind/08_get_virtctl.sh
  _includes/scriptlets/quickstart_kind/10_create_vm.sh
  _includes/scriptlets/quickstart_kind/11_get_vms.sh
  _includes/scriptlets/quickstart_kind/12_get_vms_yaml.sh
  _includes/scriptlets/quickstart_kind/13_virtctl_start_vm.sh
  _includes/scriptlets/quickstart_kind/14_get_vmis.sh
  _includes/scriptlets/quickstart_kind/15_get_vmis_yaml.sh
  _includes/scriptlets/quickstart_kind/16_virtctl_serial_console.sh
  _includes/scriptlets/quickstart_kind/17_virtctl_vnc_console.sh
  _includes/scriptlets/quickstart_kind/18_virtctl_stop_vm.sh
  _includes/scriptlets/quickstart_kind/19_kubectl_delete_vm.sh
  _includes/scriptlets/quickstart_kind/99_kind_delete.sh
  _includes/scriptlets/quickstart_kind/test_spec.yaml
  _layouts/homepage.html
  assets/images/kind-logo.png
  pages/quickstart_kind.md
Labels: approved, dco-signoff: yes, kind/website, lgtm, size/L

#441 Push to master on source updates
  .travis.yml
Labels: dco-signoff: yes, size/XS

#348 Add premonition support for admonitions
  Gemfile
  _config.yml
  _posts/2019-08-01-KubeVirt-CR-Condition-Types-Rename.markdown
  _sass/_premonition.scss
  css/main.scss
Labels: approved, dco-signoff: yes, kind/blog, kind/website, lgtm, size/M

#444 Define folder to use for GH publishing
  .travis.yml
Labels: dco-signoff: yes, size/XS

#447 Fix branch link
  _posts/2019-07-12-website-roadmap.markdown
Labels: dco-signoff: yes, kind/blog

#445 Disable future posts until date arrives
  _config.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#446 Incorporate autochangelog creation by Release autobot 🚗---->🤖
  .travis.yml
  _posts/2018-03-08-changelog-v0.3.0.markdown
  _posts/2018-04-06-changelog-v0.4.0.markdown
  _posts/2018-05-04-changelog-v0.5.0.markdown
  _posts/2018-06-11-changelog-v0.6.0.markdown
  _posts/2018-07-04-changelog-v0.7.0.markdown
  _posts/2018-09-06-changelog-v0.8.0.markdown
  _posts/2018-10-04-changelog-v0.9.0.markdown
  _posts/2018-11-08-changelog-v0.10.0.markdown
  _posts/2018-12-06-changelog-v0.11.0.markdown
  _posts/2019-01-11-changelog-v0.12.0.markdown
  _posts/2019-01-15-changelog-v0.13.0.markdown
  _posts/2019-02-04-changelog-v0.14.0.markdown
  _posts/2019-03-05-changelog-v0.15.0.markdown
  _posts/2019-04-05-changelog-v0.16.0.markdown
  _posts/2019-05-06-changelog-v0.17.0.markdown
  _posts/2019-06-05-changelog-v0.18.0.markdown
  _posts/2019-07-05-changelog-v0.19.0.markdown
  _posts/2019-08-09-Kubevirt-CR-Condition-Types-Rename-Now-ACTIVE.markdown
  _posts/2019-08-09-changelog-v0.20.0.markdown
  _posts/2019-09-09-changelog-v0.21.0.markdown
  _posts/2019-10-10-changelog-v0.22.0.markdown
  _posts/2019-11-04-changelog-v0.23.0.markdown
  _posts/2019-12-03-changelog-v0.24.0.markdown
  _posts/2020-01-13-changelog-v0.25.0.markdown
  scripts/update_changelog.sh
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XL

#453 Add 404 custom page for GH
  404.html
Labels: approved, dco-signoff: yes, lgtm, size/XS

#454 Try to fix 404 behavior
  404.html
Labels: dco-signoff: yes, size/XS

#455 Fix doc search
  docs.html
  search.json
Labels: approved, dco-signoff: yes, lgtm, size/S

#452 Reenable search functionality in website
  _includes/header.html
  _layouts/search.html
  search.html
Labels: approved, dco-signoff: yes, kind/website, lgtm, size/L

#456 Show 2020 posts
  _data/blogs_toc.yml
  pages/blogs/2020/posts.md
Labels: approved, dco-signoff: yes, kind/bug, kind/website, lgtm, size/M

#457 Tell GH to ignore Jekyll
  .travis.yml
Labels: dco-signoff: yes, size/XS

#448 Dinamically generate amis
  .travis.yml
  _data/amis.json
  pages/ec2.md
Labels: approved, dco-signoff: yes, kind/website, lgtm, size/M

#458 Backend for galleria
  _includes/head.html
  _layouts/post.html
Labels: approved, dco-signoff: yes, kind/website, lgtm, size/M

#460 Use relative links in search template
  _layouts/search.html
Labels: dco-signoff: yes, kind/website, size/S

#461 Fix date to match filename
  _posts/2019-11-28-KubeVirt_basic_operations_video.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XS

#462 Match year in filename
  _posts/2020-01-21-KubeVirt_lab3_upgrade.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XS

#463 Autocomplete suggestions
  _includes/header.html
  _sass/_autocomplete.scss
  css/main.scss
Labels: approved, dco-signoff: yes, kind/website, lgtm, size/L

#465 Do not submit search form if empty
  _includes/header.html
Labels: approved, dco-signoff: yes, lgtm, size/XS

#467 Filter search index contents
  _layouts/search.html
Labels: approved, dco-signoff: yes, kind/enhancement, kind/website, lgtm, size/XS

#468 Do more filtering
  _layouts/search.html
Labels: approved, dco-signoff: yes, kind/website, lgtm, size/XS

#469 Exclude files without plugin from indexing
  _layouts/search.html
Labels: approved, dco-signoff: yes, kind/website, lgtm, size/XS

#442 Blogpost about Steve's and Chand's talk in Kubecon NA 2019
  _posts/2020-02-01-KubeVirt_Intro-Virtual_Machine_Management_on_Kubernetes.md
  assets/2020-01-29-KubeVirt_Intro-Virtual_Machine_Management_on_Kubernetes/containers_and_vms.png
  assets/2020-01-29-KubeVirt_Intro-Virtual_Machine_Management_on_Kubernetes/kubevirt_environment.png
  assets/2020-01-29-KubeVirt_Intro-Virtual_Machine_Management_on_Kubernetes/pod_networking.png
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/L
