Repository kubevirt/kubevirt.github.io, pull requests merged in 2020-11, with the labels that each got.

#650 Update TODO list
  TODO.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#653 Fix broken links
  _posts/2018-05-08-KubeVirt-objects.markdown
  pages/quickstart_cloud.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/S

#654 Fix broken link
  _posts/2019-11-22-jenkins-ci-server-upgrade-and-jobs-for-kubevirt.markdown
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XS

#655 lab2: update the version of the Fedora image
  labs/manifests/pvc_fedora.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#657 Update ssh command in Lab2
  _includes/scriptlets/lab2/17_ssh_from_outer_minikube.sh
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/XS

#649 Correct commit with signiture for pull/450 and https://github.com/ira…
  .yaspeller.json
  _galleries/2020-01-31-DevConfCZ2020-in-pictures.md
  assets/galleria/devconfcz2020.json
Labels: approved, dco-signoff: yes, lgtm, size/M

#658 Fix kubernetes-nmstate links
  _posts/2020-10-21-Multiple-Network-Attachments-with-bridge-CNI.markdown
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XS
