Repository kubevirt/kubevirt.github.io, pull requests merged in 2020-04, with the labels that each got.

#554 blog post: KubeVirt Architecture Fundamentals
  _posts/2020-04-28-KubeVirt-Architecture-Fundamentals.md
Labels: dco-signoff: yes, kind/blog, size/M

#555 blog post: outlining KubeVirt security fundamentals
  _posts/2020-04-29-KubeVirt-Security-Fundamentals.md
  assets/2020-04-29-KubeVirt-Security-Fundamentals/component-view.png
  assets/2020-04-29-KubeVirt-Security-Fundamentals/trusted-v-untrusted-boundary.png
Labels: dco-signoff: yes, kind/blog, size/L

#556 blog post: outlining KubeVirt operation fundamentals
  _posts/2020-04-30-KubeVirt-Operation-Fundamentals.md
Labels: dco-signoff: yes, kind/blog, size/M

#558 Fix typo file
  .yaspeller.json
  _posts/2020-04-29-KubeVirt-Security-Fundamentals.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/S

#559 Fix link to minikube docs
  _posts/2018-06-20-Hello-KubeVirt-on-Minikube.markdown
  pages/quickstart_minikube.md
Labels: dco-signoff: yes, kind/blog, lgtm, size/XS
