Repository kubevirt/kubevirt.github.io, pull requests merged in 2020-07, with the labels that each got.

#580 blogpost about common templates.
  .yaspeller.json
  _posts/2020-07-01-Common_templates.md
  assets/2020-07-01-Common_templates/create_template.jpg
  assets/2020-07-01-Common_templates/create_vm.jpg
  assets/2020-07-01-Common_templates/operator.jpg
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/L

#581 Blog post for minikube and kubevirt addon
  .yaspeller.json
  _posts/2020-07-20-Minikube_KubeVirt_Addon.md
  assets/2020-07-20-Minikube_KubeVirt_Addon/1.png
  assets/2020-07-20-Minikube_KubeVirt_Addon/2.png
  assets/2020-07-20-Minikube_KubeVirt_Addon/3.png
  assets/2020-07-20-Minikube_KubeVirt_Addon/4.png
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M

#583 Add new kubevirt-dev channel, fixed slack icon, move 'req invite' to …
  _includes/footer.html
  pages/community.html
Labels: dco-signoff: yes, lgtm, size/M
