Repository kubevirt/kubevirt.github.io, pull requests merged in 2020-05, with the labels that each got.

#560 fixing broken links to the user-guide webpage in multiple blogposts
  _posts/2019-01-22-An-overview-to-KubeVirt-metrics.markdown
  _posts/2019-03-14-More-about-Kubevirt-metrics.markdown
  _posts/2019-07-29-How-To-Import-VM-into-Kubevirt.markdown
  _posts/2019-07-30-NodeDrain-KubeVirt.markdown
  _posts/2019-10-23-KubeVirt_k8s_crio_from_scratch_installing_KubeVirt.md
  _posts/2019-10-30-KubeVirt_storage_rook_ceph.md
  _posts/2019-11-28-KubeVirt_basic_operations_video.md
  _posts/2019-12-04-KubeVirt_lab1_use_kubevirt.md
  _posts/2019-12-10-KubeVirt_lab2_experiment_with_cdi.md
  _posts/2020-01-21-KubeVirt_lab3_upgrade.md
  _posts/2020-01-24-OKD-web-console-install.md
  _posts/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso.md
  _posts/2020-02-25-Advanced-scheduling-with-affinity-rules.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M

#561 vm image usage patterns blog post
  .yaspeller.json
  _posts/2020-05-12-KubeVirt-VM-Image-Usage-Patterns.md
Labels: dco-signoff: yes, kind/blog, lgtm, size/L

#562 Video homepage
  _includes/footer.html
  _includes/head.html
  _includes/header.html
  _layouts/homepage.html
  _sass/_autocomplete.scss
  _sass/_hero.scss
  _sass/_inputs.scss
  _sass/_navigation.scss
  js/video.popup.js
Labels: dco-signoff: no, kind/website, lgtm, needs-ok-to-test, size/L

#563 Fix link to prow job definition
  _posts/2019-10-31-prow-jobs-for-kubevirt.markdown
Labels: dco-signoff: yes, kind/blog, size/XS

#552 Document on Live Migration in KubeVirt
  .yaspeller.json
  _posts/2020-03-22-Live-migration.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/L

#565 SELinux blog post
  .travis.yml
  .yaspeller.json
  _posts/2020-05-25-SELinux-from-basics-to-KubeVirt.md
  assets/2020-05-25-SELinux-from-basics-to-KubeVirt/kubernetes.svg
  assets/2020-05-25-SELinux-from-basics-to-KubeVirt/kubevirt.svg
  assets/2020-05-25-SELinux-from-basics-to-KubeVirt/libvirt.svg
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, kind/blog, kind/website, lgtm, size/XL
