Repository kubevirt/kubevirt.github.io, pull requests merged in 2020-08, with the labels that each got.

#603 Fix Liquid syntax errors
  _posts/2018-10-03-KubeVirt-Network-Rehash.markdown
  pages/blogs/date.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M

#610 Use a newer Ruby version in travis-ci
  .travis.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#615 Update to Vagrant Getting-started guide url to fix HTMLproofer failures.
  _posts/2019-06-04-Kubevirt-vagrant-provider.markdown
Labels: approved, bug, dco-signoff: yes, kind/blog, lgtm, size/XS

#607 Update kubevirt on minikube quickstart page
  .yaspeller.json
  _includes/found_a_bug.md
  _includes/labs-description.md
  _includes/scriptlets/quickstart_minikube/00_verify_nested_virt.sh
  _includes/scriptlets/quickstart_minikube/01_minikube_config_memory.sh
  _includes/scriptlets/quickstart_minikube/02_minikube_config_vm_driver.sh
  _includes/scriptlets/quickstart_minikube/03_start_minikube.sh
  _includes/scriptlets/quickstart_minikube/04_setenv_version.sh
  _includes/scriptlets/quickstart_minikube/05_deploy_operator.sh
  _includes/scriptlets/quickstart_minikube/06_check_operator_running.sh
  _includes/scriptlets/quickstart_minikube/07_verify_virtualization.sh
  _includes/scriptlets/quickstart_minikube/08_emulate_vm_extensions.sh
  _includes/scriptlets/quickstart_minikube/09_deploy_kubevirt.sh
  _includes/scriptlets/quickstart_minikube/11_get_virtctl.sh
  _includes/scriptlets/quickstart_minikube/13_get_vms.sh
  _includes/scriptlets/quickstart_minikube/14_get_vms_yaml.sh
  _includes/scriptlets/quickstart_minikube/16_get_vmis.sh
  _includes/scriptlets/quickstart_minikube/17_get_vmis_yaml.sh
  _includes/scriptlets/quickstart_minikube/19_virtctl_vnc_console.sh
  _includes/scriptlets/quickstart_minikube/21_kubectl_delete_vm.sh
  _includes/scriptlets/quickstart_minikube/22_minikube_delete.sh
  _posts/2019-04-17-Hyper-Converged-Operator.markdown
  pages/quickstart_minikube.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/L

#614 Add vm-import-operator blog post
  .yaspeller.json
  _posts/2020-08-06-Import-VM-from-oVirt.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/L

#617 Remove linux-x86_64 from KubeVirt on minikube quickstart guide
  pages/quickstart_minikube.md
Labels: approved, dco-signoff: yes, lgtm, size/XS
