Repository kubevirt/kubevirt.github.io, pull requests merged in 2020-09, with the labels that each got.

#622 Update to fix links and containerdisk
  _posts/2018-05-16-KubeVirt-API-Access-Control.markdown
  _posts/2018-11-16-new-volume-types.markdown
  labs/kubernetes/lab1.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/S

#626 Fix labs-description: Remove localhost:24000 from hrefs
  _includes/labs-description.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/XS

#628 Link fix to satisy CI
  _posts/2019-10-30-KubeVirt_storage_rook_ceph.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XS

#627 Adds controller-lifecycle-operator-sdk meta tag to support vanity import
  .yaspeller.json
  _includes/head.html
  pages/controller-lifecycle-operator-sdk.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#619 Update README to add cmd for link checker
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#630 Update README to add cmd for link checker (2nd try)
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#612 Packaged issue fixes from UXD team
  _includes/footer.html
  _layouts/homepage.html
  _layouts/labs.html
  _layouts/videos.html
  _sass/_base.scss
  _sass/_buttons.scss
  _sass/_hero.scss
  _sass/_layout.scss
  assets/images/katacoda.svg
  assets/images/kind.svg
  blogs/index.html
  index.html
  labs/kubernetes/lab1.md
  labs/kubernetes/lab2.md
  labs/kubernetes/lab3.md
  pages/blogs/date.md
  pages/blogs/news.md
  pages/blogs/releases.md
  pages/blogs/uncategorized.md
  pages/blogs/updates.md
  pages/labs.md
  pages/quickstart_kind.md
  pages/quickstart_minikube.md
Labels: approved, dco-signoff: yes, kind/website, lgtm, size/XL
