Repository kubevirt/kubevirt.github.io, pull requests merged in 2020-10, with the labels that each got.

#632 Fix spelling of slack channel subtext
  pages/community.html
Labels: approved, dco-signoff: yes, lgtm, size/XS

#635 Add CNCF references and updated copyright notices
  _includes/footer.html
  assets/images/cncf-color.png
Labels: approved, dco-signoff: yes, lgtm, size/S

#631 Multiple Network Attachment with bridge CNI
  .yaspeller.json
  Gemfile
  _config.yml
  _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XL

#637 Revert "Multiple Network Attachment with bridge CNI (#631)"
  .yaspeller.json
  Gemfile
  _config.yml
  _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XL

#640 Update our documentation to point to the container disk images we currently support
  _posts/2018-05-16-KubeVirt-API-Access-Control.markdown
  _posts/2018-06-21-Run-Istio-with-kubevirt.markdown
  _posts/2018-09-11-KubeVirt-Memory-Overcommit.markdown
  _posts/2018-09-12-attaching-to-multiple-networks.markdown
  _posts/2018-11-16-new-volume-types.markdown
  _posts/2019-06-04-Kubevirt-vagrant-provider.markdown
  assets/2019-02-22-federated-kubevirt/federated_vm.yaml
  labs/manifests/vm.yaml
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/S

#638 Attaching to multiple networks followup 2
  .yaspeller.json
  Gemfile
  _config.yml
  _posts/2020-10-21-Multiple-Network-Attachments-with-bridge-CNI.markdown
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XL

#643 Added go-import for ssp-operator
  .yaspeller.json
  _includes/head.html
  pages/ssp-operator.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#645 Fix Multi Net attachmetns with CNI post
  Gemfile
  _config.yml
  _posts/2020-10-21-Multiple-Network-Attachments-with-bridge-CNI.markdown
  assets/images/kubevirt-linux-bridge-vm-to-vm.svg
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/L

#646 Fix broken links in a blog post
  _posts/2019-12-17-KubeVirt_UI_options.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XS

#647 Make the popup video auto-play when open
  js/video.popup.js
Labels: approved, dco-signoff: yes, lgtm, size/XS

#648 Fix broken links in historical pages
  _posts/2018-10-09-containerized-data-importer.markdown
  _posts/2019-07-08-kubevirt-with-ansible-part-2.markdown
  _posts/2019-10-31-jenkins-jobs-for-kubevirt-lab-validation.markdown
  pages/quickstart_kind.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/S
