Repository kubevirt/kubevirt.github.io, pull requests merged in 2020-03, with the labels that each got.

#532 Add internal anchor to installation section
  _posts/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XS

#533 Disable default language for code formatter
  _config.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#534 Remove workaround for admonitions not on first column
  Gemfile
  _posts/2019-09-09-CNCF-Sandbox.md
  _posts/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/S

#536 Fix width
  _posts/2018-04-25-KubeVirt-Network-Deep-Dive.markdown
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M

#538 Ignore youtube links
  Rakefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#541 fixing possible xss attack through the search results
  _layouts/search.html
Labels: approved, dco-signoff: yes, kind/website, lgtm, size/XS

#542 Adds spelling check support before commiting and on CI validations
  .pre-commit-config.yaml
  .travis.yml
  .yaspellerrc
  GUIDELINES.md
  README.md
  _galleries/2020-02-03-Fosdem2020-communty-presence.md
  _includes/labs-description.md
  _posts/2017-07-18-role-of-libvirt.md
  _posts/2017-07-18-technology-comparison.md
  _posts/2018-05-04-Deploying-KubeVirt-on-a-Single-oVirt-VM.markdown
  _posts/2018-05-16-Use-GlusterFS-Cloning-with-KubeVirt.markdown
  _posts/2018-10-03-KubeVirt-Network-Rehash.markdown
  _posts/2018-10-10-CDI-DataVolumes.markdown
  _posts/2018-11-16-new-volume-types.markdown
  _posts/2018-11-20-ignition-support.markdown
  _posts/2018-11-26-kubevirt-at-kubecon-na.markdown
  _posts/2019-04-17-Hyper-Converged-Operator.markdown
  _posts/2019-07-12-website-roadmap.markdown
  _posts/2019-07-29-How-To-Import-VM-into-Kubevirt.markdown
  _posts/2019-10-09-KubeVirt_k8s_crio_from_scratch.md
  _posts/2019-10-16-KubeVirt_k8s_crio_from_scratch_installing_kubernetes.md
  _posts/2019-10-23-KubeVirt_k8s_crio_from_scratch_installing_KubeVirt.md
  _posts/2019-10-30-KubeVirt_storage_rook_ceph.md
  _posts/2019-10-31-jenkins-jobs-for-kubevirt-lab-validation.markdown
  _posts/2019-10-31-prow-jobs-for-kubevirt.markdown
  _posts/2019-11-12-kubecon-na-2019.md
  _posts/2019-11-22-jenkins-ci-server-upgrade-and-jobs-for-kubevirt.markdown
  _posts/2019-12-17-KubeVirt_UI_options.md
  _posts/2020-01-24-OKD-web-console-install.md
  _posts/2020-02-01-KubeVirt_Intro-Virtual_Machine_Management_on_Kubernetes.md
  _posts/2020-02-06-KubeVirt_deep_dive-virtualized_gpu_workloads.md
  _posts/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso.md
  _posts/2020-02-25-Advanced-scheduling-with-affinity-rules.md
  package-lock.json
  package.json
  pages/alicloud.md
  pages/cloud.md
  pages/quickstart_minikube.md
Labels: approved, dco-signoff: yes, kind/blog, kind/enhancement, lgtm, size/XXL

#543 Adjust precommit configuration for code files
  .pre-commit-config.yaml
  scripts/update_changelog.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#544 Correct misspelling in Fabian's surname
  .yaspeller.json
  _posts/2017-07-18-role-of-libvirt.md
  _posts/2017-07-18-technology-comparison.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XS

#548 Ignore 429 errors with html-proofer
  Rakefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#546 Update the copyright line in the license file
  LICENSE
Labels: dco-signoff: yes, lgtm, size/XS

#547 Some issue found showing some code blocks in the "KubeVirt: installing Microsoft Windows from an ISO" blogpost
  _posts/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso.md
Labels: dco-signoff: yes, kind/blog, lgtm, size/XS

#545 Point to yaspeller repository for checking spelling via pre-commit
  .pre-commit-config.yaml
  .yaspeller.json
Labels: approved, dco-signoff: yes, lgtm, size/S

#551 amend to the PR windows_blogpost_issue
  _posts/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso.md
  package-lock.json
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M
