Repository kubevirt/kubevirt.github.io, pull requests merged in 2020-06, with the labels that each got.

#569 Fix link to the user guide in lab3
  .yaspeller.json
  labs/kubernetes/lab3.md
Labels: dco-signoff: yes, lgtm, size/XS

#572 clarify nested virtualization option for kind quick-start
  pages/quickstart_kind.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#574 Fix broken link to kubectl proxy doc
  _posts/2019-11-11-Access-Virtual-Machines-graphic-console-using-noVNC.markdown
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XS

#564 Update OWNERS
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/S

#577 Fix a few broken links in blog posts
  .gitignore
  _posts/2018-04-25-KubeVirt-Network-Deep-Dive.markdown
  _posts/2018-05-08-KubeVirt-objects.markdown
  _posts/2018-05-16-KubeVirt-API-Access-Control.markdown
  manifest.json
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M

#571 Create blog post for KubeVirt + MS Win workloads
  .yaspeller.json
  _posts/2020-06-22-win_workload_in_k8s.md
  _sass/_zoom.scss
  assets/2020-06-22-win_workload_in_k8s/1-1.png
  assets/2020-06-22-win_workload_in_k8s/1-2.png
  assets/2020-06-22-win_workload_in_k8s/1-3.png
  assets/2020-06-22-win_workload_in_k8s/1-4.png
  assets/2020-06-22-win_workload_in_k8s/2-1.png
  assets/2020-06-22-win_workload_in_k8s/2-2.png
  assets/2020-06-22-win_workload_in_k8s/2-3.png
  assets/2020-06-22-win_workload_in_k8s/2-4.png
  assets/2020-06-22-win_workload_in_k8s/2-5.png
  assets/2020-06-22-win_workload_in_k8s/2-6.png
  assets/2020-06-22-win_workload_in_k8s/service_jellyfin.yaml
  assets/2020-06-22-win_workload_in_k8s/vm_testvm.yaml
  css/main.scss
Labels: approved, dco-signoff: yes, kind/blog, kind/website, lgtm, size/L

#578 Create blog post for KubeVirt + footnote title fix
  _posts/2020-06-22-win_workload_in_k8s.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XS

#579 Remove stale blog post about KubeVirt on minikube
  _posts/2018-06-20-Hello-KubeVirt-on-Minikube.markdown
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/L
