Repository kubevirt/kubevirt.github.io, pull requests merged in 2020-12, with the labels that each got.

#659 updates labs page
  _layouts/labs.html
Labels: approved, dco-signoff: yes, kind/website, lgtm, size/XS

#642 Create blog post for KubeVirt RunStrategies
  .yaspeller.json
  _posts/2020-05-12-KubeVirt-VM-Image-Usage-Patterns.md
  _posts/2020-12-04-run_strategies.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M

#660 Add custom user agent to HTMLProofer
  Rakefile
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XS

#662 Fix NAD example
  _posts/2020-10-21-Multiple-Network-Attachments-with-bridge-CNI.markdown
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XS

#664 Add go-import paths for hostpath-provisioner{,-operator}
  .yaspeller.json
  _includes/head.html
  pages/hostpath-provisioner-operator.md
  pages/hostpath-provisioner.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#535 Blog post: Customizing images for containerized VMs
  .yaspeller.json
  _posts/2020-12-10-Customizing-images-for-containerized-vms.md
  assets/2020-12-01-Customizing-images-for-containerized-vms/cockpit-first-page.png
  assets/2020-12-01-Customizing-images-for-containerized-vms/cockpit-gui.png
  assets/2020-12-01-Customizing-images-for-containerized-vms/create_blueprint.png
  assets/2020-12-01-Customizing-images-for-containerized-vms/devstation-centos8.toml
  assets/2020-12-01-Customizing-images-for-containerized-vms/diagram-customizing-images.png
  assets/2020-12-01-Customizing-images-for-containerized-vms/kubevirt_okd.png
  assets/2020-12-01-Customizing-images-for-containerized-vms/okd_is_devstation.png
  assets/2020-12-01-Customizing-images-for-containerized-vms/packages_version.png
  assets/2020-12-01-Customizing-images-for-containerized-vms/users.png
Labels: approved, dco-signoff: yes, kind/blog, kind/website, lgtm, size/XXL

#641 Add "Monitoring KubeVirt VMs from the inside" blog post
  .yaspeller.json
  _posts/2020-12-10-Monitoring-KubeVirt-VMs-from-the-inside.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/L

#663 Update broken link to Fedora-Cloud qcow2 img. Remove version where p…
  _posts/2020-05-12-KubeVirt-VM-Image-Usage-Patterns.md
  _posts/2020-12-10-Customizing-images-for-containerized-vms.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M

#636 Update for tooling in support of KubeVirt v 1.0 / Docs revamp
  .travis.yml
  .yaspeller.json
  Gemfile
  Makefile
  Rakefile
  check_selectors.js
  pages/quickstart_kind.md
Labels: approved, dco-signoff: yes, kind/bug, kind/enhancement, kind/website, lgtm, size/XXL
