Repository kubevirt/kubevirt.github.io, pull requests merged in 2020-02, with the labels that each got.

#473 Enable comments by default on articles
  _layouts/post.html
Labels: approved, dco-signoff: yes, kind/website, lgtm, size/XS

#475 Omit versions that include a dash when computing $KUBEVIRT_VERSION
  _includes/scriptlets/quickstart_kind/02_setenv_version.sh
  _includes/scriptlets/quickstart_minikube/04_setenv_version.sh
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/XS

#477 Add slack notifications
  .travis.yml
Labels: approved, dco-signoff: yes, lgtm, size/S

#478 Point chat to Slack instead of IRC
  pages/community.html
Labels: approved, dco-signoff: yes, lgtm, size/XS

#479 Typo in slack channel name
  pages/community.html
Labels: approved, dco-signoff: yes, lgtm, size/XS

#470 blogpost about the video KubeVirt_deep_dive-virtualized_gpu_workloads
  _posts/2020-02-06-KubeVirt_deep_dive-virtualized_gpu_workloads.md
  assets/2020-02-06-KubeVirt_deep_dive-virtualized_gpu_workloads/NVIDIA_usecase_keyfeatures.png
  assets/2020-02-06-KubeVirt_deep_dive-virtualized_gpu_workloads/gpu_pass_lifecycle.png
  assets/2020-02-06-KubeVirt_deep_dive-virtualized_gpu_workloads/gpu_pass_yaml.png
  assets/2020-02-06-KubeVirt_deep_dive-virtualized_gpu_workloads/gpus_on_kubevirt.png
  assets/2020-02-06-KubeVirt_deep_dive-virtualized_gpu_workloads/kubevirt_gpu_passthrough.png
  assets/2020-02-06-KubeVirt_deep_dive-virtualized_gpu_workloads/kubevirt_infrastructure_convergence.png
  assets/2020-02-06-KubeVirt_deep_dive-virtualized_gpu_workloads/kubevirt_one_stack.png
  assets/2020-02-06-KubeVirt_deep_dive-virtualized_gpu_workloads/kubevirt_virtual_machine.png
  assets/2020-02-06-KubeVirt_deep_dive-virtualized_gpu_workloads/kubevirt_vm_launch_flow.png
  assets/2020-02-06-KubeVirt_deep_dive-virtualized_gpu_workloads/kubevirt_volumes.png
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/L

#459 Automated year grouping of articles
  _data/blogs_toc.yml
  pages/blogs/2017/posts.md
  pages/blogs/2018/posts.md
  pages/blogs/2019/posts.md
  pages/blogs/2020/posts.md
  pages/blogs/date.md
Labels: approved, dco-signoff: yes, kind/enhancement, kind/website, lgtm, size/L

#472 Showcase slack link
  _includes/footer.html
  _sass/_footer.scss
Labels: approved, dco-signoff: yes, kind/website, lgtm, size/S

#476 Update guidelines to show admonitions
  GUIDELINES.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#480 Notify on failures/changes
  .travis.yml
Labels: approved, dco-signoff: yes, kind/website, lgtm, size/XS

#483 Never notify on success
  .travis.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#482 Fix loop generation
  _layouts/search.html
Labels: approved, dco-signoff: yes, kind/website, lgtm, size/XS

#486 Exclude documents with no title
  _layouts/search.html
Labels: approved, dco-signoff: yes, kind/website, lgtm, size/XS

#491 Index authors on search
  _layouts/search.html
Labels: approved, dco-signoff: yes, kind/enhancement, kind/website, lgtm, size/XS

#493 Fix link to rbac
  _posts/2018-10-09-containerized-data-importer.markdown
Labels: approved, dco-signoff: yes, kind/blog, kind/bug, lgtm, size/XS

#495 Use --future for rendering future-dated posts
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#484 Update slack link to point to the #virtualization channel
  _includes/footer.html
Labels: approved, dco-signoff: yes, lgtm, size/XS

#499 Add link to get an invite to K8S slack instance
  pages/community.html
Labels: approved, dco-signoff: yes, lgtm, size/XS

#501 Move old markdown to article
  _posts/2017-07-18-technology-comparison.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/S

#494 Kubevirt windows blogpost
  _posts/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso.md
  assets/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso/kubevirt_install_windows.mp4
  assets/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso/win2k12.yml
  assets/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso/win2k12_download_iso.png
  assets/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso/win2k12_download_iso_64.png
  assets/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso/windows2k12_install.png
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/L

#506 code inside a bullet bugfix try1
  _posts/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/S

#507 Add Katacoda scenario links
  labs/kubernetes/lab1.md
  labs/kubernetes/lab2.md
  labs/kubernetes/lab3.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#508 Use post_url macro
  _posts/2018-09-12-attaching-to-multiple-networks.markdown
  _posts/2018-10-03-KubeVirt-Network-Rehash.markdown
  _posts/2020-01-24-OKD-web-console-install.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M

#509 Pingback to updated article
  _posts/2018-04-25-KubeVirt-Network-Deep-Dive.markdown
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XS

#471 Fosdem 2020 pictures from twitter
  _galleries/2020-02-03-Fosdem2020-communty-presence.md
  assets/galleria/fosdem2020.json
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M

#474 Add gallery category under blogs
  _config.yml
  _data/site_nav_pages.yml
  _layouts/search.html
  pages/gallery.md
Labels: approved, dco-signoff: yes, kind/website, lgtm, size/M

#512 Use article tags for populating keywords suggestions
  _includes/header.html
Labels: approved, dco-signoff: yes, lgtm, size/XS

#503 Remove obsolete files
  _layouts/docs.html
  _layouts/kubernetes.html
  _layouts/ocp.html
  assets/images/labs/ocp/catalog-home.png
  assets/images/labs/ocp/kubevirt-apb-config.png
  assets/images/labs/ocp/kubevirt-apb-info.png
  assets/images/labs/ocp/openshift-console-kube-system.png
  assets/images/labs/ocp/openshift-console-login.png
  assets/images/labs/ocp/openshift-console-view-all.png
  assets/images/labs/ocp/provisioned-kubevirt.png
  assets/images/labs/ocp/virtualization-tab.png
  docs.html
  pages/community/contributing.md
  search.json
Labels: approved, dco-signoff: yes, kind/website, lgtm, size/L

#513 Remove additional files
  _galleries/2020-02-03-Fosdem2020-communty-presence.md
  _posts/2019-10-31-jenkins-jobs-for-kubevirt-lab-validation.markdown
  js/simple-jekyll-search.min.js
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/L

#514 Set default tags to article tags
  _includes/metas-ogp.html
Labels: approved, dco-signoff: yes, lgtm, size/XS

#516 Put netlify banner on mainpage as per requirements for their service
  _includes/footer.html
  pages/privacy.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#520 Fix links
  _posts/2018-08-08-kubevirtci.markdown
Labels: dco-signoff: yes, kind/blog, size/S

#518 Add linenumbers
  _config.yml
  _includes/footer.html
  _includes/header.html
  _sass/_syntax.scss
  css/main.scss
  js/clipboard.min.js
  js/copy.js
Labels: approved, dco-signoff: yes, kind/blog, kind/website, lgtm, size/L

#519 Reduce image size and use photoswipe gallery
  _config.yml
  _includes/head.html
  _layouts/default.html
  _layouts/post.html
  _posts/2018-04-25-KubeVirt-Network-Deep-Dive.markdown
  _posts/2018-10-03-KubeVirt-Network-Rehash.markdown
  assets/images/kubevirt-skydive-vm-to-vm.png
  assets/images/skydive_haproxy_to_vm.png
  assets/images/skydive_vm_to_vm.png
  js/photoswipe-page.js
Labels: approved, dco-signoff: yes, kind/blog, kind/website, lgtm, size/L

#522 Scrollcode
  _sass/_syntax.scss
  js/copy.js
Labels: approved, dco-signoff: yes, kind/website, lgtm, size/M

#521 Fix title and use generic includes
  _includes/labs-description.md
  _includes/scriptlets/lab1/test_spec.yaml
  _includes/scriptlets/lab2/test_spec.yaml
  _includes/scriptlets/quickstart_cloud/00_verify_nested_virt.sh
  _includes/scriptlets/quickstart_cloud/04_setenv_version.sh
  _includes/scriptlets/quickstart_cloud/05_deploy_operator.sh
  _includes/scriptlets/quickstart_cloud/06_check_operator_running.sh
  _includes/scriptlets/quickstart_cloud/07_verify_virtualization.sh
  _includes/scriptlets/quickstart_cloud/08_emulate_vm_extensions.sh
  _includes/scriptlets/quickstart_cloud/09_deploy_kubevirt.sh
  _includes/scriptlets/quickstart_cloud/11_get_virtctl.sh
  _includes/scriptlets/quickstart_cloud/13_get_vms.sh
  _includes/scriptlets/quickstart_cloud/14_get_vms_yaml.sh
  _includes/scriptlets/quickstart_cloud/16_get_vmis.sh
  _includes/scriptlets/quickstart_cloud/17_get_vmis_yaml.sh
  _includes/scriptlets/quickstart_cloud/19_virtctl_vnc_console.sh
  _includes/scriptlets/quickstart_cloud/21_kubectl_delete_vm.sh
  _includes/scriptlets/quickstart_kind/test_spec.yaml
  _includes/scriptlets/quickstart_minikube/test_spec.yaml
  pages/cloud.md
  pages/quickstart_kind.md
  pages/quickstart_minikube.md
Labels: approved, dco-signoff: yes, kind/blog, kind/website, lgtm, size/XL

#504 Blog post: Advanced scheduling with affinity rules
  _posts/2020-02-20-Advanced-scheduling-with-affinity-rules.md
  assets/2020-02-20-Advanced-scheduling-with-affinity-rules/kubevirt-blog-affinity.resized.png
Labels: dco-signoff: yes, kind/blog, size/XL

#523 Document how to use gallery
  GUIDELINES.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#524 Disable line numbers
  _config.yml
  js/copy.js
Labels: approved, dco-signoff: yes, lgtm, size/S

#525 Changed publication date to affinity blog post
  _posts/2020-02-25-Advanced-scheduling-with-affinity-rules.md
  assets/2020-02-25-Advanced-scheduling-with-affinity-rules/kubevirt-blog-affinity.resized.png
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M

#526 Show youtube link to KubeVirt channel
  _includes/footer.html
  _sass/_footer.scss
Labels: approved, dco-signoff: yes, kind/website, lgtm, size/S

#529 Add site verification
  _includes/head.html
Labels: approved, dco-signoff: yes, lgtm, size/XS

#530 Update link
  _includes/footer.html
Labels: approved, dco-signoff: yes, lgtm, size/XS

#531 Amend code
  _includes/head.html
Labels: approved, dco-signoff: yes, lgtm, size/XS
