Repository kubevirt/kubevirt.github.io, pull requests merged in 2021-01, with the labels that each got.

#668 Fix minikube -> kind typo
  pages/quickstart_kind.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/XS

#669 remove disqus code
  _layouts/default.html
  _layouts/post.html
Labels: approved, dco-signoff: yes, kind/website, lgtm, size/S

#672 Add blog post to announce the KubeVirt Summit
  .yaspeller.json
  _posts/2019-10-16-KubeVirt_k8s_crio_from_scratch_installing_kubernetes.md
  _posts/2021-01-12-KubeVirt-Summit-announce.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M

#675 Add import path for https://github.com/kubevirt/cpu-nfd-plugin
  _includes/head.html
  pages/cpu-nfd-plugin.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#678 Add a landing page for the KubeVirt Summit
  _posts/2021-01-12-KubeVirt-Summit-announce.md
  pages/summit.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M

#677 fir labels in Live Migration template
  _posts/2020-03-22-Live-migration.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, needs-ok-to-test, size/XS

#680 fixed
  _layouts/homepage.html
Labels: approved, dco-signoff: yes, kind/website, lgtm, size/XS

#682 Update summit sponsorship
  _posts/2020-02-25-Advanced-scheduling-with-affinity-rules.md
  pages/summit.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XS

#683 Remove the CfP from the summit page
  pages/summit.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#685 Update summit times and registration details
  pages/summit.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#686 Update the summit event link to the info page
  pages/summit.md
Labels: approved, dco-signoff: yes, lgtm, size/XS
