Repository kubevirt/kubevirt.github.io, pull requests merged in 2021-02, with the labels that each got.

#688 Add a session schedule for the KubeVirt Summit
  .yaspeller.json
  pages/summit.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#689 Update event link
  pages/summit.md
Labels: dco-signoff: yes, size/XS

#690 Update summit page to reflect it finished
  pages/summit.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#692 Fix user guide links
  _posts/2018-04-25-KubeVirt-Network-Deep-Dive.markdown
  _posts/2018-05-08-KubeVirt-objects.markdown
  _posts/2018-05-16-KubeVirt-API-Access-Control.markdown
  _posts/2018-11-16-new-volume-types.markdown
  _posts/2019-01-22-An-overview-to-KubeVirt-metrics.markdown
  _posts/2019-03-14-More-about-Kubevirt-metrics.markdown
  _posts/2019-07-29-How-To-Import-VM-into-Kubevirt.markdown
  _posts/2019-07-30-NodeDrain-KubeVirt.markdown
  _posts/2019-10-23-KubeVirt_k8s_crio_from_scratch_installing_KubeVirt.md
  _posts/2019-10-30-KubeVirt_storage_rook_ceph.md
  _posts/2019-11-28-KubeVirt_basic_operations_video.md
  _posts/2019-12-04-KubeVirt_lab1_use_kubevirt.md
  _posts/2019-12-10-KubeVirt_lab2_experiment_with_cdi.md
  _posts/2020-01-21-KubeVirt_lab3_upgrade.md
  _posts/2020-01-24-OKD-web-console-install.md
  _posts/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso.md
  _posts/2020-02-25-Advanced-scheduling-with-affinity-rules.md
  _posts/2020-03-22-Live-migration.md
  _posts/2020-05-12-KubeVirt-VM-Image-Usage-Patterns.md
  _posts/2020-05-25-SELinux-from-basics-to-KubeVirt.md
  _posts/2020-06-22-win_workload_in_k8s.md
  _posts/2020-12-10-Customizing-images-for-containerized-vms.md
  labs/kubernetes/lab1.md
  labs/kubernetes/lab3.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/L

#687 update containerDisk image to use quay.io
  labs/manifests/vm.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#697 Increase the PVC size to host the Fedora image
  labs/manifests/pvc_fedora.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#699 Corrected link text
  _posts/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, ok-to-test, size/XS

#684 Tooling
  .yaspeller.json
  Makefile
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/L

#702 Removing for website issue
  pages/hostpath-provisioner-operator.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#704 Re-added hp operator page during debug of 404.
  pages/hostpath-provisioner-operator.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/XS

#705 Removing for website issue
  pages/hostpath-provisioner-operator.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#706 Readded
  pages/hostpath-provisioner-operator.md
Labels: approved, dco-signoff: yes, lgtm, size/XS
