Repository kubevirt/kubevirt.github.io, pull requests merged in 2021-05, with the labels that each got.

#734 Update description field for 2021-04-30-intel-vgpu-kubevirt blog post
  _posts/2021-04-30-intel-vgpu-kubevirt.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#736 Migrate KubeVirt shared cal to the CNCF account
  _config.yml
  pages/community.html
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#737 Fixed merge artifacts
  README.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#740 Update to v1
  labs/manifests/vm.yaml
  labs/manifests/vm1_pvc.yml
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/XS

#739 Fixed Quickstart Labs Version Command
  pages/quickstart_cloud.md
  pages/quickstart_kind.md
  pages/quickstart_minikube.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/XS
