Repository kubevirt/kubevirt.github.io, pull requests merged in 2021-09, with the labels that each got.

#789 Added automatic detection of SELinux
  Makefile
Labels: size/XS, lgtm, approved, dco-signoff: yes

#791 Changed link to shorten and remove branch name in posts
  _posts/2019-07-30-NodeDrain-KubeVirt.markdown
  _posts/2019-10-23-KubeVirt_k8s_crio_from_scratch_installing_KubeVirt.md
Labels: size/XS, kind/blog, lgtm, approved, needs-ok-to-test, dco-signoff: yes

#790 Update KubeVirt refs master -> main
  _posts/2018-04-25-KubeVirt-Network-Deep-Dive.markdown
  _posts/2018-06-07-Non-Dockerized-Build.markdown
  _posts/2018-07-03-Unit-Test-Howto.markdown
  _posts/2018-08-08-kubevirtci.markdown
  _posts/2018-09-12-attaching-to-multiple-networks.markdown
  _posts/2018-10-09-containerized-data-importer.markdown
  _posts/2019-04-17-Hyper-Converged-Operator.markdown
  _posts/2019-07-08-kubevirt-with-ansible-part-2.markdown
  _posts/2019-07-29-How-To-Import-VM-into-Kubevirt.markdown
  _posts/2019-08-01-KubeVirt-CR-Condition-Types-Rename.markdown
  _posts/2020-01-24-OKD-web-console-install.md
  _posts/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso.md
  _posts/2020-05-12-KubeVirt-VM-Image-Usage-Patterns.md
  _posts/2020-12-10-Customizing-images-for-containerized-vms.md
  _posts/2020-12-10-Monitoring-KubeVirt-VMs-from-the-inside.md
  _posts/releases/2017-11-07-Kube-Virt-v004.markdown
  _posts/releases/2017-12-08-Kube-Virt-v010.markdown
  _posts/releases/2018-01-05-Kube-Virt-v020.markdown
Labels: size/L, kind/blog, lgtm, approved, ok-to-test, dco-signoff: yes

#795 Blog post: Import AWS AMIs as KubeVirt Golden Images
  _posts/2021-09-21-Importing-EC2-to-KubeVirt.md
Labels: size/L, kind/blog, lgtm, approved, dco-signoff: yes

#796 Fix istio post linting
  _posts/2019-10-31-prow-jobs-for-kubevirt.markdown
  _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
Labels: size/S, kind/blog, lgtm, approved, ok-to-test, dco-signoff: yes

#797 First attempt at a data driven adopters consumed from kubevirt/kubevirt
  _data/adopters.py
  _data/adopters.yml
  assets/images/adopters/Civo.png
  assets/images/adopters/NVIDIA.png
  assets/images/adopters/RedHatInc.png
Labels: size/L, kind/website, lgtm, approved, dco-signoff: yes
