Repository kubevirt/kubevirt.github.io, pull requests merged in 2021-10, with the labels that each got.

#800 Fix for lint CI issues
  Makefile
Labels: size/S, lgtm, approved, dco-signoff: yes

#798 Remove duplicate text
  _posts/2019-07-29-How-To-Import-VM-into-Kubevirt.markdown
Labels: size/XS, kind/blog, lgtm, approved, ok-to-test, dco-signoff: yes

#803 Added SIG - Performance & Scale Playlist to community meetings section
  pages/videos/community/meetings.md
Labels: size/S, lgtm, approved, ok-to-test, dco-signoff: yes
