Repository kubevirt/kubevirt.github.io, pull requests merged in 2021-06, with the labels that each got.

#746 Update to OWNERS file
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/S

#743 Fix check_spelling exit codes plus a couple cosmetics
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/S

#747 Update yaspeller dictionary file
  .yaspeller.json
Labels: approved, dco-signoff: yes, lgtm, size/XL

#745 Fix check_spelling exit codes, speed plus cosmetics
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/S

#749 Fix bad merge artifacts
  Makefile
  _posts/2021-04-30-intel-vgpu-kubevirt.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/M

#750 Update dictionary file
  .yaspeller.json
Labels: approved, dco-signoff: yes, lgtm, size/XS

#748 Update README
  README.md
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, size/L

#752 New KubeVirt Live Migration Lab
  _data/labs_toc.yml
  _includes/quickstarts/multi_node_minikube.md
  _includes/scriptlets/lab1/01_get_vm_manifest.sh
  _includes/scriptlets/lab1/02_create_testvm.sh
  _includes/scriptlets/lab1/04_start_testvm.sh
  _includes/scriptlets/lab1/06_connect_to_testvm_console.sh
  _includes/scriptlets/lab1/07_stop_testvm.sh
  _includes/scriptlets/lab2/12_connect_to_vm1_console.sh
  _includes/scriptlets/migration/01_enable_livemigration_feature.sh
  _includes/scriptlets/migration/03_expose_ports.sh
  _includes/scriptlets/migration/04_serve_http.sh
  _includes/scriptlets/migration/05_find_http.sh
  _includes/scriptlets/migration/06_test_http.sh
  _posts/2019-10-30-KubeVirt_storage_rook_ceph.md
  labs/kubernetes/lab3.md
  labs/kubernetes/migration.md
  pages/quickstart_minikube.md
Labels: approved, dco-signoff: yes, kind/blog, kind/website, lgtm, ok-to-test, size/L

#755 Add dhiller to approvers
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#756 Create build target for CI
  Makefile
  _galleries/2020-02-03-Fosdem2020-communty-presence.md
  _posts/2019-10-31-prow-jobs-for-kubevirt.markdown
  scripts/update_changelog.sh
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/S

#757 Updating README
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#758 Remove travis-ci script
  .travis.yml
Labels: approved, dco-signoff: yes, lgtm, size/M
