Repository kubevirt/kubevirt.github.io, pull requests merged in 2021-08, with the labels that each got.

#768 Adding self to approvers/reviewers
  OWNERS
Labels: size/XS, lgtm, dco-signoff: yes

#770 Update privacy policy and mailing address for correct CNCF links.
  pages/privacy.md
Labels: size/XS, lgtm, approved, ok-to-test, dco-signoff: yes

#767 Fix lint errors
  .markdownlint.yaml
  .markdownlintignore
  _posts/2019-10-09-KubeVirt_k8s_crio_from_scratch.md
  _posts/2019-10-16-KubeVirt_k8s_crio_from_scratch_installing_kubernetes.md
  _posts/2019-10-23-KubeVirt_k8s_crio_from_scratch_installing_KubeVirt.md
  _posts/2019-10-30-KubeVirt_storage_rook_ceph.md
  _posts/2019-12-17-KubeVirt_UI_options.md
  _posts/2020-01-24-OKD-web-console-install.md
  _posts/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso.md
  _posts/2020-02-25-Advanced-scheduling-with-affinity-rules.md
  _posts/2020-03-22-Live-migration.md
  _posts/2020-04-28-KubeVirt-Architecture-Fundamentals.md
  _posts/2020-04-29-KubeVirt-Security-Fundamentals.md
  _posts/2020-04-30-KubeVirt-Operation-Fundamentals.md
  _posts/2020-05-12-KubeVirt-VM-Image-Usage-Patterns.md
  _posts/2020-05-25-SELinux-from-basics-to-KubeVirt.md
  _posts/2020-06-22-win_workload_in_k8s.md
  _posts/2020-07-01-Common_templates.md
  _posts/2020-07-20-Minikube_KubeVirt_Addon.md
  _posts/2020-08-06-Import-VM-from-oVirt.md
  _posts/2020-12-04-run_strategies.md
  _posts/2020-12-10-Customizing-images-for-containerized-vms.md
  _posts/2020-12-10-Monitoring-KubeVirt-VMs-from-the-inside.md
  _posts/2021-01-12-KubeVirt-Summit-announce.md
  _posts/2021-03-03-KubeVirt-Summit-Wrap-Up.md
  _posts/2021-04-21-Automated-Windows-Installation-With-Tekton-Pipelines.md
  _posts/2021-04-30-intel-vgpu-kubevirt.md
  _posts/2021-07-16-kubevirt-api-auth.md
  pages/privacy.md
  pages/quickstart_cloud.md
  pages/quickstart_kind.md
  pages/quickstart_minikube.md
  pages/summit.md
Labels: size/XL, kind/blog, lgtm, approved, needs-ok-to-test, dco-signoff: yes

#771 Add phoracek to owners
  OWNERS
Labels: size/XS, lgtm, approved, dco-signoff: yes

#762 Update index page
  Rakefile
  _data/adopters.yml
  _includes/footer.html
  _layouts/default.html
  _layouts/homepage.html
  _sass/_layout.scss
  assets/images/adopters/CIVO.png
  assets/images/adopters/CLOUDFLARE.png
  assets/images/adopters/CoreWeave.png
  assets/images/adopters/EQUINIX.png
  assets/images/adopters/H3C.png
  assets/images/adopters/KUBERMATIC.png
  assets/images/adopters/NVIDIA.jpg
  assets/images/adopters/PLATFORM9.png
  assets/images/adopters/RANCHER.png
  assets/images/adopters/Red Hat.png
  assets/images/adopters/STACKPATH.png
  assets/images/adopters/SUSE.png
  assets/images/adopters/minikube.png
  assets/images/adopters/oVirt.png
  assets/images/adopters/okd.png
  assets/images/adopters/rancher.png
  index.html
Labels: size/L, kind/website, lgtm, approved, dco-signoff: yes

#774 Add phoracek to OWNERS
  OWNERS
Labels: size/XS, lgtm, approved, dco-signoff: yes

#769 Blog post about VMs with Istio
  _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
  assets/2021-08-13-Virtual-machines-in-Istio-service-mesh/istio-blog-vmi-istio-inbound-traffic.png
  assets/2021-08-13-Virtual-machines-in-Istio-service-mesh/topology-graph.png
Labels: size/L, kind/blog, lgtm, approved, dco-signoff: yes

#776 Repair default template
  _layouts/default.html
Labels: size/M, kind/website, lgtm, approved, dco-signoff: yes

#788 Changed link to shorten and remove branch name
  _includes/scriptlets/lab2/08_get_vm_manifest.sh
Labels: size/XS, lgtm, approved, dco-signoff: yes

#787 Delete duplicate and unused rancher logo
  assets/images/adopters/rancher.png
Labels: size/XS, lgtm, approved, ok-to-test, dco-signoff: yes
