Repository kubevirt/kubevirt.github.io, pull requests merged in 2021-11, with the labels that each got.

#813 Update adopter.py, allow for other filetypes, add some checking
  _data/adopters.py
Labels: size/S, kind/website, lgtm, approved, dco-signoff: yes

#815 Adding arm to index page as end-user per KubeVirt ADOPTERS
  _data/adopters.yml
  assets/images/adopters/arm.svg
Labels: size/M, kind/enhancement, kind/website, lgtm, approved, dco-signoff: yes

#816 Broken link fix
  _posts/weekly/2017-10-28-This-Week-in-Kube-Virt-8.markdown
Labels: size/XS, kind/blog, lgtm, approved, ok-to-test, dco-signoff: yes

#818 Fixed #817, Moving Netlify configuration to local toml
  Makefile
  Rakefile
  netlify.toml
Labels: size/S, kind/blog, lgtm, approved, dco-signoff: yes, do-not-merge/invalid-commit-message

#819 Replaced old master branch name
  GUIDELINES.md
  Makefile
  README.md
  _includes/quickstarts/kubectl.md
  package.json
Labels: size/M, lgtm, approved, dco-signoff: yes
