Repository kubevirt/kubevirt.github.io, pull requests merged in 2021-03, with the labels that each got.

#708 KubeVirt Summit wrap up
  .yaspeller.json
  _layouts/homepage.html
  _posts/2021-03-03-KubeVirt-Summit-Wrap-Up.md
  pages/summit.md
Labels: approved, dco-signoff: yes, kind/blog, kind/website, lgtm, size/XL

#709 Fixed VM name myvm->testvm
  labs/kubernetes/lab1.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/XS

#714 refactor README.md
  Makefile
  README.md
  _posts/2018-05-04-Deploying-KubeVirt-on-a-Single-oVirt-VM.markdown
Labels: approved, dco-signoff: yes, kind/blog, lgtm, ok-to-test, size/L

#722 Added slack invite to community page
  pages/community.html
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/XS
