Repository kubevirt/kubevirt.github.io, pull requests merged in 2021-04, with the labels that each got.

#723 Update lab2 for latest minikube
  _includes/scriptlets/lab2/01_get_storage_manifest.sh
  _includes/scriptlets/lab2/02_create_storage.sh
  _includes/scriptlets/lab2/05_view_cdi_deployment.sh
  _includes/scriptlets/lab2/06_create_fedora_cloud_instance.sh
  _includes/scriptlets/lab2/16_minikube_vm_ip.sh
  _posts/2019-10-31-prow-jobs-for-kubevirt.markdown
  labs/kubernetes/lab2.md
  labs/manifests/pvc_fedora.yml
  labs/manifests/storage-setup.yml
  pages/summit.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, ok-to-test, size/L

#727 Add blog post Automatic Windows Installation With Tekton Pipelines
  _posts/2021-04-21-Automated-Windows-Installation-With-Tekton-Pipelines.md
  assets/2021-04-21-Automated-Windows-Installation-With-Tekton-Pipelines/win-started.png
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XL

#729 fix highlighting in a Automated Windows Installation blog post
  _posts/2021-04-21-Automated-Windows-Installation-With-Tekton-Pipelines.md
Labels: approved, dco-signoff: yes, kind/blog, lgtm, size/XS

#728 Issue#711
  .yaspeller.json
  _posts/2021-04-30-intel-vgpu-kubevirt.md
  assets/2021-04-30-intel-vgpu-kubevirt/fishgl-gpu.png
  assets/2021-04-30-intel-vgpu-kubevirt/fishgl-nogpu.png
Labels: approved, dco-signoff: yes, kind/blog, lgtm, ok-to-test, size/XL
