Repository kubevirt/kubevirt.github.io, pull requests merged in 2022-08, with the labels that each got.

#839 Windows 11 installation blog post
  _posts/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso.md
  _posts/2022-08-02-KubeVirt-installing_Microsoft_Windows_11_from_an_iso.md
Labels: size/L, kind/blog, lgtm, approved, dco-signoff: yes

#860 blog: Add instancetype post
  _posts/2022-08-12-KubeVirt-Introduction-of-instancetypes.md
Labels: size/L, kind/blog, lgtm, approved, dco-signoff: yes

#861 Reestablish links to new Killercoda scenarios
  Rakefile
  _layouts/homepage.html
  assets/images/katacoda-logo.png
  assets/images/katacoda.svg
  assets/images/killercoda_logo.svg
  labs/kubernetes/lab1.md
  labs/kubernetes/lab2.md
Labels: size/S, kind/website, lgtm, approved, dco-signoff: yes

#864 Remove use of DEBUG env var from Makefile
  Makefile
Labels: size/S, lgtm, approved, dco-signoff: yes

#856 Corrected markdown lint
  _posts/2020-12-10-Customizing-images-for-containerized-vms.md
  _posts/2021-10-13-Running-Realtime-Workloads.md
  _posts/2022-06-28-KubeVirt-at-KubeCon-EU-2022.md
  pages/summit.md
Labels: size/M, kind/blog, lgtm, approved, dco-signoff: yes
