Repository kubevirt/kubevirt.github.io, pull requests merged in 2022-01, with the labels that each got.

#822 Update Summit Page for 2022 Summit
  pages/summit.md
Labels: size/L, lgtm, approved, needs-ok-to-test, dco-signoff: yes

#823 Last cleanup of offensive language.
  .pre-commit-config.yaml
  README.md
  _config/src/package.json
Labels: size/XS, lgtm, approved, dco-signoff: yes

#824 Add Summit Schedule.
  pages/summit.md
Labels: size/M, lgtm, approved, ok-to-test, dco-signoff: yes

#825 Adding post to link to and socialize the second kubevirt summit
  _posts/2022-01-24-KubeVirt-Summit-2022.md
Labels: size/M, kind/blog, lgtm, approved, dco-signoff: yes
