Repository kubevirt/kubevirt.github.io, pull requests merged in 2022-05, with the labels that each got.

#840 Add go import config for Node Maintenance Operator
  _includes/head.html
  pages/node-maintenance-operator.md
Labels: size/XS, lgtm, approved, dco-signoff: yes

#843 Fix for broken links to adopters on index page
  index.html
Labels: size/XS, lgtm, approved, ok-to-test, dco-signoff: yes

#841 Add new vendor puzl.ee
  _data/adopters.yml
  assets/images/adopters/puzl.png
Labels: size/XS, kind/website, lgtm, approved, ok-to-test, dco-signoff: yes

#837 Load-balancer for virtual machines on bare metal Kubernetes clusters
  _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
Labels: size/L, kind/blog, lgtm, approved, dco-signoff: yes
