Repository kubevirt/kubevirt.github.io, pull requests merged in 2022-02, with the labels that each got.

#828 Change to Wednesday Summit schedule per presenter requirements.
  pages/summit.md
Labels: size/S, lgtm, approved, needs-ok-to-test, dco-signoff: yes

#826 blog: add post about dedicated migration networks
  _posts/2022-01-25-Dedicated-migration-network.md
Labels: size/M, kind/blog, lgtm, approved, dco-signoff: yes

#832 Minor fix for title of one talk, per speaker
  pages/summit.md
Labels: size/XS, lgtm, approved, dco-signoff: yes
