Repository kubevirt/kubevirt.github.io, pull requests merged in 2023-09, with the labels that each got.

#917 Adding point to announce new blogs on mailing list
  GUIDELINES.md
Labels: size/XS, lgtm, approved, dco-signoff: yes

#916 blog: Managing KubeVirt VMs with Ansible
  _posts/2023-09-05-Managing-KubeVirt-VMs-with-Ansible.md
Labels: size/L, kind/blog, lgtm, approved, dco-signoff: yes

#913 localnet: various small fixes
  _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
Labels: size/M, kind/blog, lgtm, approved, dco-signoff: yes

#918 Add blog on KubeVirt and Cluster Autoscaler
  _posts/2023-09-06-KubeVirt-on-autoscaling-nodes.md
Labels: size/XL, kind/blog, lgtm, approved, needs-ok-to-test, dco-signoff: yes
