Repository kubevirt/kubevirt.github.io, pull requests merged in 2023-03, with the labels that each got.

#894 summit 23 blog post for newsreel
  _posts/2023-03-03-KubeVirt-Summit-2023.md
Labels: size/M, kind/blog, lgtm, approved, dco-signoff: yes

#896 update codeblock for virtctl
  _includes/quickstarts/virtctl.md
Labels: size/XS, lgtm, approved, ok-to-test, dco-signoff: yes

#898 Adjusting for daylight savings
  pages/summit.md
Labels: size/XS, lgtm, approved, dco-signoff: yes

#897 Summit reschedule (swapping sessions)
  pages/summit.md
Labels: size/M, lgtm, approved, dco-signoff: yes
