Repository kubevirt/kubevirt.github.io, pull requests merged in 2023-01, with the labels that each got.

#886 Updating summit.md for KubeVirt Summit 2023
  pages/summit.md
Labels: size/M, lgtm, approved, dco-signoff: yes

#887 s/sandbox/incubating in footer
  _includes/footer.html
Labels: size/XS, lgtm, approved, dco-signoff: yes

#890 Fix Adopters in website
  _data/adopters.py
  _data/adopters.yml
  assets/images/adopters/Deckhouse.svg
  assets/images/adopters/Killercoda.svg
  assets/images/adopters/Trilio.svg
  assets/images/adopters/osbuildoperator.png
Labels: size/L, kind/website, lgtm, approved, dco-signoff: yes
