Repository kubevirt/kubevirt.github.io, pull requests merged in 2024-07, with the labels that each got.

#959 Updating our website Videos section
  _data/video_toc.yml
  pages/videos.html
  pages/videos/community/meetings.md
  pages/videos/demos.md
  pages/videos/interviews.md
  pages/videos/kubevirt-summit.md
  pages/videos/talks.md
  pages/videos/tech-demos.md
Labels: size/L, kind/website, lgtm, approved, dco-signoff: yes

#941 Review and update of lab1
  labs/kubernetes/lab1.md
Labels: size/S, lgtm, approved, dco-signoff: yes

#962 Add go-import for kubevirt.io/vm-console-proxy project
  _includes/head.html
Labels: size/XS, lgtm, approved, dco-signoff: yes
